- desk/src/pages/portal/Ticket.vue
Issue: when the user tries to send a message it did not work
solution: there was a typo in the method called while submitting the conversation
> fix: text editor issue in customer portal

- frappedesk/patches.txt
- frappedesk/setup/install.py
Adds redirect for `/support/` to `/support/tickets`
> fix: add redirect for support/ -> support/tickets

- desk/src/pages/desk/Desk.vue
Resolves these issues
Error while trying to login
Recursive setup API call issue
https://user-images.githubusercontent.com/22856401/181667283-86e3252e-e8ce-4ba1-8818-3a31bf5a94bb.mp4
> fix: error on desk login

- desk/src/components/desk/ticket/ConversationCard.vue
- desk/src/components/portal/ticket/ConversationCard.vue
- desk/src/pages/desk/Ticket.vue
- desk/src/pages/portal/Ticket.vue
- Refactor reply box text editor height in agent and customer ticket views
- Remove unwanted right padding inside conversation cards, for desk and customer portal
> fix: text editor styling / result in conversation cards

- frappedesk/setup/install.py
Error when adding app to site - sql query error.
Changed "Agent Groups" to "Agent Group".
> removed add app to site bug - sql query

- desk/src/components/global/CustomTextEditor.vue
> fix: text editor newline issue

- desk/src/components/desk/global/CustomIcons.vue
- desk/src/components/desk/knowledge_base/TopNavbar.vue
- desk/src/components/desk/tickets/NewTicketDialog.vue
- desk/src/components/global/CustomTextEditor.vue
- desk/src/components/global/Toast.vue
- desk/src/components/portal/NavBar.vue
- desk/src/pages/desk/Desk.vue
- desk/src/pages/portal/NewTicket.vue
- frappedesk/api/settings.py
- frappedesk/frappedesk/doctype/frappe_desk_settings/frappe_desk_settings.json
- frappedesk/templates/kb_base_template.html
Setting Helpdesk Name via toast
https://user-images.githubusercontent.com/22856401/185541451-57195917-4185-4d68-8c9c-5c40bfd933aa.mov
> fix: ui issues

- desk/src/components/portal/ticket/CustomerSatisfactionFeedback.vue
> fix: customer portal feedback comment

- desk/src/pages/desk/knowledge_base/Category.vue
> feat: add input validation for new category creation

- desk/src/components/desk/ticket/ActionPanel.vue
> feat: add shortcut keys ticket status change

- desk/src/pages/desk/Ticket.vue
- frappedesk/api/ticket.py
> fix: reverse order of activities in ticket history section

- desk/src/components/desk/ticket/ActionPanel.vue
- desk/src/components/global/Autocomplete.vue
Resolves #642 
https://user-images.githubusercontent.com/22856401/186330059-288b4d99-9bb1-418f-850c-61759c46d749.mov
> refactor: replace dropdown and use autocomplete in ticket action panel

- desk/src/components/desk/settings/policies/SlaPolicyListItem.vue
- desk/src/pages/desk/settings/sla/SlaPolicies.vue
- desk/src/pages/desk/settings/sla/SlaPolicy.vue
- frappedesk/frappedesk/doctype/frappe_desk_settings/frappe_desk_settings.json
- frappedesk/frappedesk/doctype/service_holiday_list/service_holiday_list_dashboard.py
- frappedesk/frappedesk/doctype/service_holiday_list/test_service_holiday_list.py
- frappedesk/frappedesk/doctype/sla/sla.js
- frappedesk/frappedesk/doctype/sla/sla.json
- frappedesk/frappedesk/doctype/sla/sla.py
- frappedesk/frappedesk/doctype/sla/sla_dashboard.py
- frappedesk/frappedesk/doctype/sla/test_sla.py
- frappedesk/frappedesk/doctype/ticket/ticket.js
- frappedesk/frappedesk/doctype/ticket/ticket.json
- frappedesk/frappedesk/doctype/ticket/ticket.py
- frappedesk/frappedesk/report/ticket_analytics/test_ticket_analytics.py
- frappedesk/frappedesk/workspace/frappedesk/frappedesk.json
- frappedesk/hooks.py
- frappedesk/setup/install.py
> fix: erpnext compatibility issues

- desk/src/components/desk/SideBarMenu.vue
Resolves #662
- opens the tab in a new page
> feat: `Go to customer portal` opens on new tab

- desk/src/components/desk/ticket/CommentCard.vue
- desk/src/components/desk/ticket/Conversations.vue
- desk/src/pages/desk/Ticket.vue
- frappedesk/frappedesk/doctype/frappe_desk_comment/frappe_desk_comment.json
implement create/fetch comments using `Frappe Desk Comment`
> refactor: comment logic using `Frappe Desk Comment`

- frappedesk/frappedesk/doctype/frappe_desk_comment/frappe_desk_comment.json
- frappedesk/frappedesk/doctype/frappe_desk_notification/frappe_desk_notification.json
Add agent permissions to frappe desk notifications and comments
> fix: permissions for frappedesk notification and comments

- desk/src/components/desk/knowledge_base/ArticleDetails.vue
- desk/src/components/desk/knowledge_base/ArticleList.vue
- desk/src/components/desk/knowledge_base/NewCategoryDialog.vue
- desk/src/components/desk/knowledge_base/SideBarMenu.vue
- desk/src/components/global/ListManager.vue
- desk/src/pages/desk/knowledge_base/Category.vue
- desk/src/pages/desk/knowledge_base/KnowledgeBase.vue
- desk/src/router.js
- frappedesk/setup/install.py
Resolves #630
https://user-images.githubusercontent.com/22856401/187093080-e1ea5624-eabd-4a11-9463-101074037efa.mov
> fix: article & category creation and deletion

- desk/src/components/desk/global/FilterBox.vue
- desk/src/components/global/Toast.vue
Resolves #684
Resolves  #674
Resolves  #692
Resolves  #693
Resolves #694
> fix: minor issues

- desk/index.html
- desk/src/pages/desk/settings/helpdesk/HelpdeskSettings.vue
> refactor: initial page title from FrappeDesk-> Frappe Desk

- frappedesk/frappedesk/workspace/frappedesk/frappedesk.json
> feat: add `Agent Group` to Frappe Desk workspace

- frappedesk/frappedesk/doctype/article/article.json
- frappedesk/frappedesk/doctype/category/category.json
- frappedesk/patches/set_initial_order_for_articles_and_categories.py
> fix: order field issue in patch(set_initial_order_for_articles_and_categories)

- desk/package.json
- desk/yarn.lock
Resolves #717
Resolves #711
Resolves #708
> chore: update frappe-ui -> v0.0.65

- desk/src/components/desk/tickets/TicketListItem.vue
- desk/src/pages/desk/Desk.vue
> fix: avatar image in ticket list view

- desk/src/components/desk/ticket/ActionPanel.vue
- desk/src/pages/desk/Desk.vue
- frappedesk/frappedesk/doctype/ticket/ticket.json
> fix: remove notes from ticket view

- desk/src/components/desk/SideBarMenu.vue
> feat: add list of shortcut keys info

- frappedesk/templates/kb_base_template.html
> fix: code formatting issue in article page

- desk/src/components/desk/settings/agents/AgentInfo.vue
- desk/src/components/global/UserAvatar.vue
- fix: Agent rename issue
- feat: Profile pic editing
> fix: agent page

- desk/src/components/desk/SideBarMenu.vue
> fix: kb not highlighted in sidebar on selection isseus

- frappedesk/api/ticket.py
Removed `allow_guest=True` from APIs from `api/ticket.py` which did not require it.
> fix: security issues with ticket apis

- desk/src/components/global/CustomTextEditor.vue
fixes issue with autofocus on the reply box open, and insert link issue in custom text editor component
> fix: ticket reply box text editor issue

- desk/src/components/desk/ticket/ActionPanel.vue
- desk/src/components/global/Autocomplete.vue
Before
After
https://user-images.githubusercontent.com/22856401/199970037-4fba89c3-070f-422b-a17c-9f21a5d102a7.mov
> fix: autocomplete input text overflow truncate issue

- desk/src/components/desk/settings/agents/AgentRelatedInfo.vue
> feat: add mini ticket list in agent page

- desk/src/components/global/ticket_list_item/ResolutionBy.vue
- desk/src/pages/desk/Tickets.vue
- fix `due in` logic
- remove `ago` from modified col
- col resizing
> fix: ticket list issues

- frappedesk/patches.txt
- frappedesk/patches/set_home_page_to_kb.py
- frappedesk/setup/install.py
> fix: home page not redirecting to support/kb

- desk/src/components/desk/settings/SettingsTopPanel.vue
> refactor: change `New Agent` -> `Add Agent` in agent list

- frappedesk/frappedesk/workspace/frappe_desk/frappe_desk.json
Update Frappe Desk Workspace
https://github.com/frappe/desk/issues/849
> chore: update frappedesk workspace

- frappedesk/api/ticket.py
- ticket template field overrides (only set if provided)
- fix: setting contact's email_id
> fix: new ticket creation via agent portal 

- desk/src/pages/desk/Ticket.vue
- desk/src/pages/portal/ticketing/NewTicket.vue
> fix: text editor in customer portal new ticket page

- desk/src/pages/desk/Ticket.vue
Uploading Screen Recording 2022-12-27 at 11.36.50 AM.mov…
Resolves #879
> feat: add copy ticket id to clipboard

- desk/src/pages/desk/Contacts.vue
> fix: contact full name issue in contact list

- desk/src/components/desk/ticket/CommentCard.vue
- desk/src/components/desk/ticket/ConversationCard.vue
> fix: communication card styles

- desk/src/components/desk/settings/policies/SlaPolicyList.vue
> feat: add `Active` col in sla policy list

- desk/src/components/global/TicketField.vue
https://user-images.githubusercontent.com/22856401/209816018-4db56f64-892a-432b-b5a3-8f0bac16e534.mov
> feat: add agent filtering based on agent group inside ticket field component

- desk/src/components/desk/dashboard/SlaSummaryCards.vue
- desk/src/components/desk/dashboard/TicketStatusCards.vue
- desk/src/pages/desk/Dashboard.vue
> fix: dashboard ui fixes

- frappedesk/frappedesk/doctype/ticket/ticket.py
> fix: reply email subject issue

- frappedesk/frappedesk/doctype/article/article.py
- frappedesk/patches.txt
- frappedesk/patches/set_category_as_none_for_archived_articles.py
> fix: category deletion issue

- desk/src/pages/desk/settings/sla/SlaPolicy.vue
> Fix support policy UI

- desk/src/components/desk/customers/CustomerInfo.vue
- desk/src/components/desk/global/AddNewAgentsDialog.vue
- desk/src/components/desk/global/ArticleResponseDialog.vue
- desk/src/components/desk/global/CannedResponsesDialog.vue
- desk/src/components/desk/kb/CategorySelector.vue
- desk/src/components/desk/settings/agents/AgentList.vue
- desk/src/components/desk/settings/canned_responses/CannedResponseList.vue
- desk/src/components/desk/settings/canned_responses/ResponseTitleAndMessage.vue
- desk/src/components/desk/settings/emails/EmailList.vue
- desk/src/components/desk/settings/policies/SlaPolicyList.vue
- desk/src/components/desk/settings/teams/TeamInfo.vue
- desk/src/components/desk/ticket/InfoPanel.vue
- desk/src/components/desk/tickets/NewTicketDialog.vue
- desk/src/components/global/ListViewer.vue
- desk/src/components/global/ticket_list_item/TicketStatus.vue
- desk/src/pages/common/kb/Category.vue
- desk/src/pages/desk/Ticket.vue
This PR Resolves following issue:
1.Ticket status color mismatch. Resolves #928 
2.Auto-fetch customer when contact is selected in new ticket dialog. Resolves #933 
3. Scrollbar Visibility issue.
> fix: ui fixes

- desk/src/components/global/ListViewer.vue
- desk/src/pages/desk/Contacts.vue
- desk/src/pages/desk/Customers.vue
- desk/src/pages/desk/settings/agent/Agents.vue
- desk/src/pages/desk/settings/canned_response/CannedResponses.vue
- desk/src/pages/desk/settings/email/Emails.vue
- desk/src/pages/desk/settings/sla/SlaPolicies.vue
- desk/src/pages/desk/settings/team/Teams.vue
- desk/src/pages/desk/settings/ticket_type/TicketTypes.vue
Refactor list view of contacts, customers, agents, teams, ticket types, canned responses, support policies and email account.
> refactor: list view

- desk/src/pages/desk/Ticket.vue
- desk/src/pages/portal/ticketing/Ticket.vue
Resolves #915 
*Customer and agents can now edit ticket subject.
https://user-images.githubusercontent.com/73826691/214000897-47672286-1bad-424d-80d7-0ca5d861359c.mp4
> feat: edit ticket subject

- frappedesk/frappedesk/doctype/sla/sla.py
Resolves sla not updating based on condition in tickets.
> fix: update sla based on condition

- desk/src/components/desk/contacts/ContactRelatedInfo.vue
- desk/src/components/global/ListViewer.vue
- desk/src/pages/desk/Tickets.vue
It does not make any sense to have `v-if="false"` on any block. These does not look like TODO either
> fix(ui): remove blocks with `v-if="false"`

- .github/workflows/eslint.yml
> ci: add semgrep rules

- .github/workflows/eslint.yml
- commitlint.config.js
> ci: add commit lint

- desk/src/pages/desk/settings/canned_response/CannedResponses.vue
- desk/src/pages/desk/settings/email/Emails.vue
- desk/src/pages/desk/settings/sla/SlaPolicies.vue
closes https://github.com/frappe/helpdesk/issues/982
> fix(ui): highlight selected settings option

- .github/helpers/install.sh
- .github/helpers/site_config_mariadb.json
- .github/workflows/server-tests.yml
mostly copied from frappe and erpnext
> ci: add python unit tests and coverage

- frappedesk/frappedesk/doctype/frappe_desk_settings/frappe_desk_settings.json
caused by https://github.com/frappe/helpdesk/pull/1030
> fix(settings): add hidden but wanted checks

- frappedesk/frappedesk/doctype/sla/sla.py
https://github.com/frappe/frappe/pull/20255/commits/71a1cdc96eb77925b1e9e189230aafdaca0d807b
> chore: replace `get_time_zone` with `get_system_timezone`

- desk/src/components/global/kb/ArticleMiniList.vue
> feat: knowledge base: category name instead of "Articles"

- desk/src/components/global/kb/ArticleMiniList.vue
- desk/src/pages/common/kb/Article.vue
- desk/src/pages/desk/kb/Articles.vue
- desk/src/router.js
- frappedesk/api/kb.py
- frappedesk/frappedesk/doctype/article/article.json
- frappedesk/frappedesk/doctype/article/article.py
- frappedesk/frappedesk/doctype/ticket/ticket.json
> feat: article title slug in url

- desk/src/components/desk/ticket/InfoPanel.vue
> fix(ui): info panel: remove unwanted padding

- desk/src/components/global/AgentAvatar.vue
- desk/src/components/global/ListManager.vue
- frappedesk/frappedesk/doctype/agent/agent.json
- frappedesk/frappedesk/doctype/agent/agent.py
- frappedesk/frappedesk/doctype/canned_response/canned_response.json
- frappedesk/frappedesk/doctype/fd_customer/fd_customer.json
- `Agent`
- `Canned Response`
- `FD Customer`
> fix(ux): doctype permissions

- frappedesk/frappedesk/doctype/frappe_desk_settings/frappe_desk_settings.json
> chore(settings): add descriptions for workflow checkboxes (gpt ftw)

- desk/src/pages/desk/Ticket.vue
> feat(ui): ticket cc bcc improvements

- .eslintrc.js
- desk/package.json
- desk/src/App.vue
- desk/src/components/desk/tickets/AssignedInfo.vue
- desk/src/components/desk/tickets/FilterBox.vue
- desk/src/components/desk/tickets/FilterCombobox.vue
- desk/src/components/desk/tickets/PresetFilters.vue
- desk/src/components/desk/tickets/TicketSummary.vue
- desk/src/components/global/ListManager.vue
- desk/src/composables/listFilters.ts
- desk/src/composables/listManager.ts
- desk/src/main.js
- desk/src/pages/desk/Tickets.vue
- desk/src/pages/desk/Tickets.vue.bak
- desk/src/stores/auth.ts
- desk/src/stores/ticketPriority.ts
- desk/src/stores/ticketStatus.ts
- desk/tailwind.config.js
- desk/yarn.lock
- frappedesk/api/agent.py
- frappedesk/extends/client.py
- frappedesk/frappedesk/doctype/fd_preset_filter/fd_preset_filter.json
- frappedesk/frappedesk/doctype/fd_preset_filter/fd_preset_filter.py
- frappedesk/frappedesk/doctype/ticket/ticket.py
- package.json
- yarn.lock
- move page meta logic to api
- extend existing list resource from `frappe-ui`
> refactor: list manager

- desk/src/App.vue
- desk/src/components/desk/SideBarMenu.vue
- desk/src/components/desk/contacts/ContactRelatedInfo.vue
- desk/src/components/desk/kb/ArticleDetails.vue
- desk/src/components/desk/settings/agents/AgentRelatedInfo.vue
- desk/src/components/desk/ticket/ActionPanel.vue
- desk/src/components/global/ListManager.vue
- desk/src/components/global/PresetFilters.vue
- desk/src/components/portal/NavBar.vue
- desk/src/components/portal/kb/ArticleFeedback.vue
- desk/src/pages/auth/Login.vue
- desk/src/pages/auth/VerifyAccount.vue
- desk/src/pages/common/kb/Article.vue
- desk/src/pages/desk/Dashboard.vue
- desk/src/pages/desk/Desk.vue
- desk/src/pages/desk/Ticket.vue
- desk/src/pages/desk/Tickets.vue
- desk/src/pages/portal/ticketing/Impersonate.vue
- desk/src/pages/portal/ticketing/NewTicket.vue
- desk/src/pages/portal/ticketing/Ticket.vue
- desk/src/pages/portal/ticketing/Ticketing.vue
- desk/src/stores/auth.ts
- frappedesk/api/agent.py
- frappedesk/api/auth.py
replace inject/provide with pinia store (authStore)
> refactor: do not inject/provide user (logged in)

- desk/src/pages/desk/Tickets.vue
> feat: ticket list: table header background

- desk/src/pages/WebsiteRoot.vue
- desk/src/router.js
Redirect to agent portal tickets if logged in user has desk permission. Redirect to customer portal if not
> feat: `/`: redirect based on permission

- helpdesk/helpdesk/doctype/hd_agent/hd_agent.py
- helpdesk/helpdesk/doctype/hd_team_item/hd_team_item.json
> fix: field names: `hd_agent_group` -> `team`

- desk/package.json
- desk/src/App.vue
- desk/src/components/desk/sidebar/SideBar.vue
- desk/src/pages/KeymapDialog.vue
- desk/src/pages/desk/Tickets.vue
- desk/src/stores/keymap.ts
- desk/yarn.lock
- Add/remove keymaps per components
- Render keymaps list from global store
closes #964
> refactor: use pinia (global) for keymaps

- desk/src/App.vue
- desk/src/pages/auth/Signup.vue
- desk/src/router.js
- remove socket events
- use auth store
closes #1131
> fix(ux): signup

- desk/src/components/portal/tickets/TicketList.vue
- resolved and closed -> green
- open -> red
> fix(ui): customer portal: ticket badge color

- desk/src/components/desk/sidebar/SideBar.vue
- do not use hardcoded path
- get path from from `router.resolve`
> fix: sidebar: customer portal link

- desk/src/pages/desk/Tickets.vue
This reverts commit ca533980139b36f5ecce0de4a37fdf6149da2aa2.
> Revert "fix(ux): show filtered status and priority (#1163)"

- desk/src/components/desk/tickets/TicketSummary.vue
- desk/src/pages/desk/ticket/TicketSingle.vue
- desk/src/pages/desk/ticket/data.ts
> feat(ui): badge for new ticket

- desk/src/components/charts/PieChart.vue
- helpdesk/api/dashboard.py
- also limit all dataset to previous 7 days
> fix(ui): dashboard: conditionally apply `roseType`

- desk/src/pages/desk/DeskDashboard.vue
- helpdesk/api/dashboard.py
- change date limit from 7 to 30
- show an info (tooltip) saying the same
> fix(ui): dashboard: limit dashboard data to 30 days

- desk/src/pages/desk/ticket/data.ts
- desk/src/pages/desk/ticket/editor/BottomSection.vue
- desk/src/pages/desk/ticket/editor/ResponseEditor.vue
- desk/src/utils/editor.ts
- Add a debounce of `500ms`
- Disable send button conditionally
> fix(ux): response editor

- desk/src/pages/desk/ticket-list/AssignedInfo.vue
- desk/src/pages/desk/ticket-list/MainTable.vue
- also move assignment to the end
- remove extra options button
> feat: ticket list: add `customer` column

- desk/src/pages/desk/ticket/data.ts
- desk/src/pages/desk/ticket/editor/BottomSection.vue
Responses (Replies/Comments) should not be empty.
> fix: empty responses should not be allowed.

- desk/src/components/SearchComplete.vue
- desk/src/components/text-editor/TextEditor.vue
- desk/src/components/text-editor/TextEditorBottom.vue
- desk/src/pages/desk/ticket-list/ListHeader.vue
- desk/src/pages/desk/ticket-list/NewTicketDialog.vue
- desk/src/pages/desk/ticket-list/TicketList.vue
Related: https://github.com/frappe/helpdesk/issues/1208
> refactor: agent portal: new ticket dialog

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
closes https://github.com/frappe/helpdesk/issues/1248
> fix(ux): ticket before insert: remove `.save()`

- desk/src/components/desk/sidebar/SideBar.vue
- desk/src/components/desk/sidebar/SidebarLink.vue
- desk/src/components/desk/sidebar/UserMenu.vue
Reduce font size, item height and make name bold
> feat(ui): sidebar: adjust font size

- desk/src/components/charts/SingleString.vue
- desk/src/components/charts/theme.ts
- desk/src/pages/desk/ContactDialog.vue
- desk/src/pages/desk/DeskDashboard.vue
- helpdesk/api/dashboard.py
- change color scheme
- change single string card height
- add user specific tickets count - open/replied
> chore: dashboard changes

- .github/workflows/server-tests.yml
> chore: upgrade dependencies

- desk/src/composables/listManager.ts
- desk/src/pages/desk/ticket-list/AssignedInfo.vue
- desk/src/pages/desk/ticket-list/MainTable.vue
- desk/src/pages/desk/ticket-list/TicketSummary.vue
- helpdesk/extends/client.py
- helpdesk/helpdesk/doctype/hd_article/hd_article.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/hooks/contact.py
Override https://github.com/frappe/helpdesk/pull/1285
> feat: ticket: refactor

- desk/src/components/TopBar.vue
- desk/src/pages/desk/team/TeamSingle.vue
- desk/src/pages/portal/TicketSingle.vue
> feat(ui): customer portal ticket: reuse `TopBar.vue`

- desk/src/pages/WebsiteRoot.vue
- desk/src/pages/knowledge-base/KnowledgeBaseArticle.vue
- desk/src/pages/portal/TicketList.vue
- desk/src/router.js
- desk/src/stores/config.ts
- helpdesk/api/config.py
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
If enabled,
- redirect to knowledge base
- hide `new ticket` button
> feat: switch to prefer knowledge base

- desk/src/pages/desk/sla/SlaPolicy.vue
Closes the first issue mentioned in https://github.com/frappe/helpdesk/issues/1338
> fix(UX): Remove Cancel and Save/Create button at the bottom of page

- desk/src/pages/desk/contact/ContactDialog.vue
closes https://github.com/frappe/helpdesk/issues/1354
> fix(ux): contact picture buttons and labels

- desk/src/pages/desk/team/TeamSingle.vue
Earlier:
After updating (New Message):
> fix: changed empty team member message

- desk/src/pages/desk/ticket/TicketDetails.vue
- desk/src/pages/desk/ticket/data.ts
- Remove save button
- Remove keymaps
related: https://github.com/frappe/helpdesk/issues/1325
> feat(ux): ticket details: auto save

- desk/src/pages/desk/ticket/CommentItem.vue
- desk/src/pages/desk/ticket/ConversationBox.vue
- desk/src/pages/desk/ticket/PinnedComments.vue
- desk/src/pages/desk/ticket/TicketSingle.vue
- desk/src/pages/desk/ticket/data.ts
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/doctype/hd_ticket_comment/hd_ticket_comment.json
related: https://github.com/frappe/helpdesk/issues/1368
> feat: comment pin

- desk/src/pages/desk/ticket/ConversationBox.vue
closes https://github.com/frappe/helpdesk/issues/1371
> fix(ux): cc and bcc fallback

- helpdesk/consts.py
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/doctype/hd_ticket/patches/fallback_ticket_type.py
- helpdesk/setup/ticket_type.py
closes: https://github.com/frappe/helpdesk/issues/1382
> feat: default ticket priority

- desk/package.json
- desk/src/components/TabButtons.vue
- desk/src/pages/desk/ticket/TicketHistory.vue
- desk/src/pages/desk/ticket/TicketHistoryItem.vue
- desk/src/types.ts
- desk/yarn.lock
- helpdesk/helpdesk/doctype/hd_ticket/api.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
closes: https://github.com/frappe/helpdesk/issues/1385
> feat: ticket view log

- desk/src/pages/desk/ticket-list/AssignedInfo.vue
closes https://github.com/frappe/helpdesk/issues/1392
> fix: error on missing assignee

- desk/src/pages/portal/TicketSingle.vue
- desk/src/stores/ticketStatus.ts
closes https://github.com/frappe/helpdesk/issues/1395
> feat(ui): customer ticket: conditionally show text editor

- helpdesk/helpdesk/doctype/hd_ticket/api.py
closes https://github.com/frappe/helpdesk/issues/1404
> refactor: move context locals out of global scope

- helpdesk/hooks.py
- helpdesk/overrides.py
closes https://github.com/frappe/helpdesk/issues/1401
> chore: remove unwanted hook: pull support emails

- desk/src/pages/desk/ticket/PinnedComments.vue
closes: https://github.com/frappe/helpdesk/issues/1410
> fix: pinned comments: sanitise input

- helpdesk/helpdesk/doctype/hd_ticket/api.py
Solving issue #1408
Before: 
After Fix:
> fix: removed non-existing Colum in single ticket-view

- desk/src/components/charts/PieChart.vue
closes https://github.com/frappe/helpdesk/issues/1437
> chore(ui): pie chart: remove rose (area)

- desk/package.json
- desk/src/components/AttachmentItem.vue
- desk/src/components/CommunicationItem.vue
- desk/yarn.lock
For `text/plain` and `image/*`
> feat: attachment preview

- desk/src/components/AttachmentItem.vue
- Text
- Image
- Pdf
- Spreadsheet
> feat(ui): attachment: icon

- helpdesk/helpdesk/doctype/hd_ticket_feedback_option/hd_ticket_feedback_option.json
- helpdesk/helpdesk/doctype/hd_ticket_feedback_option/patches/label_as_name.py
- helpdesk/patches.txt
closes https://github.com/frappe/helpdesk/issues/1462
related https://github.com/frappe/helpdesk/pull/1464
> fix(ux): feedback: use label as name (instead of random)

- desk/src/components/CommunicationItem.vue
- desk/src/components/TimelineItem.vue
- desk/src/dayjs.ts
- desk/src/pages/desk/ticket-list/MainTable.vue
- desk/src/pages/desk/ticket-list/TicketList.vue
- desk/src/pages/desk/ticket/CommentItem.vue
- desk/src/pages/desk/ticket/TicketDetails.vue
- desk/src/pages/desk/ticket/TopBar.vue
- desk/src/pages/knowledge-base/KnowledgeBaseArticleTopView.vue
closes: https://github.com/frappe/helpdesk/issues/1491
> chore: extend dayjs

- helpdesk/helpdesk/report/ticket_analytics/ticket_analytics.js
- helpdesk/helpdesk/report/ticket_analytics/ticket_analytics.py
- wrong doctype
closes: https://github.com/frappe/helpdesk/issues/1549
> fix: report: ticket analytics

- desk/src/pages/c-layout/CLayoutNav.vue
closes: https://github.com/frappe/helpdesk/issues/1538
> fix: knowledge base link: wrong route

- helpdesk/helpdesk/doctype/hd_pause_service_level_agreement_on_status/hd_pause_service_level_agreement_on_status.json
- helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py
- helpdesk/helpdesk/doctype/hd_service_level_agreement_fulfilled_on_status/hd_service_level_agreement_fulfilled_on_status.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
https://github.com/frappe/helpdesk/issues/1554
> chore: move `first_responded_on` from sla to ticket

- .eslintrc.js
- desk/src/components/Notifications.vue
- desk/src/components/SidebarLink.vue
- desk/src/components/desk/sidebar/SideBar.vue
- desk/src/components/index.ts
- desk/src/components/notifications/Notifications.vue
- desk/src/components/notifications/NotificationsMention.vue
- desk/src/main.js
- desk/src/pages/desk/AgentRoot.vue
- desk/src/socket.ts
- desk/src/stores/notification.ts
- desk/src/stores/sidebar.ts
- desk/src/types.ts
- helpdesk/helpdesk/doctype/hd_notification/hd_notification.json
- helpdesk/helpdesk/doctype/hd_notification/hd_notification.py
- helpdesk/helpdesk/doctype/hd_notification/utils.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/mixins/mentions.py
- helpdesk/utils.py
> feat: notifications tab

- desk/src/pages/ticket/TicketCustomerTemplateFields.vue
- desk/src/pages/tickets/TicketsCustomer.vue
> chore(ux): Show response and resolution details on customer portal

- helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py
- refactored from crm
- time_diff_in_seconds args in previous code were in incorrect order https://github.com/frappe/helpdesk/blob/5efc39dee03f7a705948dd3ae8b14294897e4716/helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py#L306
Fixes: https://github.com/frappe/helpdesk/issues/1639
> fix: Negative resolution time

- desk/src/components/BreadCrumbs.vue
- desk/src/pages/ticket/TicketBreadcrumbs.vue
Closes https://github.com/frappe/helpdesk/issues/1653
> feat: Copy ticket id when clicked on subject in breadcrumb

- desk/src/pages/ticket/TicketCustomerTemplateFields.vue
- desk/src/pages/tickets/TicketsCustomer.vue
closes https://github.com/frappe/helpdesk/issues/1665
> display ticket priority on customer ticket list and detail view

- desk/src/pages/ticket/TicketNew.vue
> Revert "chore: added temporary banner for offsite"

- desk/src/pages/ticket/TicketAgent2.vue
- desk/src/pages/tickets/TicketsAgent2.vue
- desk/src/pages/tickets/TicketsAgentList2.vue
- helpdesk/api/doc.py
feat: added pagination in new tickets agent list
fix: reply button out of view in mobile screens
> updates in new tickets agent list

- desk/src/pages/ticket/TicketNew.vue
reverts https://github.com/frappe/helpdesk/pull/1700/ since ticket type also impacts ticket priority and thus SLA
> fix: revert pr 1700

- desk/src/index.css
- desk/src/pages/tickets/TicketsAgent.vue
- desk/src/pages/tickets/TicketsAgentList.vue
save pagelength per user, closes: https://github.com/frappe/helpdesk/issues/1707
fix: word break
fix: list footer color
> Misc fixes

- desk/src/components/ColumnSettings.vue
- desk/src/components/Filter.vue
- desk/src/pages/knowledge-base/KnowledgeBaseArticle.vue
- helpdesk/api/doc.py
- helpdesk/helpdesk/report/first_response_time_for_tickets/first_response_time_for_tickets.py
- helpdesk/helpdesk/report/ticket_analytics/ticket_analytics.js
- helpdesk/helpdesk/report/ticket_analytics/ticket_analytics.py
fixes: 
Knowledge Base - Not able to add new articles #1687
cannot add or edit anything in knowledge base -> new article page and error when clicking publish new article. #1676
Helpdesk Reports #1649
feat:
Cannot search via ticket ID on portal #1644
> Knowledge Base, Report and filter fixes

- desk/src/components/MultipleAvatar.vue
closes https://github.com/frappe/helpdesk/issues/1745
> fix: _assign font color and size

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
fixes https://github.com/frappe/helpdesk/issues/1775
> fix: check for presence of contact

- desk/src/pages/ticket/TicketTextEditor.vue
fixes https://github.com/frappe/helpdesk/issues/1770
> fix: remove attachment should only remove selected file

- desk/src/components/TimelineItem.vue
- desk/src/components/notifications/Notifications.vue
- desk/src/dayjs.ts
- desk/src/pages/knowledge-base/KnowledgeBaseArticleTopEdit.vue
- desk/src/pages/ticket/TicketComment.vue
- desk/src/pages/ticket/TicketCommunication.vue
- desk/src/pages/ticket/TicketCustomerTemplateFields.vue
- desk/src/pages/ticket/TicketDetails.vue
- desk/src/pages/tickets/TicketsAgentList.vue
- desk/src/pages/tickets/TicketsCustomer.vue
- desk/src/stores/auth.ts
- helpdesk/api/auth.py
fixes https://github.com/frappe/helpdesk/issues/1621
> fix: render timeago based on user timezone

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/doctype/hd_ticket/test_hd_ticket.py
fixes https://github.com/frappe/helpdesk/issues/1779
> fix: agent not found error for non agent

- .github/workflows/server-tests.yml
> fix(ci): add token for code coverage

- .github/workflows/server-tests.yml
- desk/src/components/UniInput2.vue
- desk/src/components/ticket/TicketAgentDetails.vue
- desk/src/components/ticket/TicketAgentFields.vue
- desk/src/components/ticket/TicketAgentSidebar.vue
- desk/src/pages/desk/agent/AgentList.vue
**Issue:**
Sidebar Fields
1. First Response
2. Resolution
Changes in both of the above fields are reflected only after refresh.
**Solution**
https://github.com/frappe/helpdesk/assets/65544983/f656c374-8419-4406-a2e7-24a19e90758e
> fix: reactivity in sidebar

- desk/src/components/UniInput2.vue
- desk/src/components/ticket/TicketAgentDetails.vue
- desk/src/components/ticket/TicketAgentFields.vue
- desk/src/components/ticket/TicketAgentSidebar.vue
- desk/src/types.ts
- helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py
This PR solves these issues
1. Update the subject of the ticket from the Sidebar.
2. Show proper border on FormControl fields in Sidebar.
3. Fix SLA comparison between response & resolution time.
> fix: update customer from sidebar and sidebar enhancement

- desk/src/components/MultiSelect.vue
- desk/src/components/Pill.vue
- desk/src/components/desk/global/NewContactDialog.vue
- desk/src/pages/desk/contact/ContactDialog.vue
- desk/src/pages/desk/contact/ContactList.vue
- desk/src/pages/desk/team/TeamSingle.vue
- desk/src/types.ts
**What changed?**
1. You can now create contact from the UI, we were unable to do so because Autocomplete component did not show any customers.
2. Reactivity was broken while creating contact and updating contact, fixed it.
3. Refactored NewContactDialog.
- Individual states were used for each Input.
- Added Object for creating Inputs.
- Fixed reactivity when a contact is created
4. Converted NewContactDialog component to Composition API from Options API.
5. Created a Pill component, and replaced it with wherever pills were created in Team & Contact page.
6. Refactored Contact page with relevant components to have types.
> refactor: contact page

- desk/src/components/ticket/TicketsAgentList.vue
- desk/src/pages/TicketsAgent.vue
When we add "rating" column in TicketAgentList we get:
**Solution:**
Handle column type of Rating and add rating column
closes:
#1848
> fix: show rating component in ticket list view

- desk/src/pages/KnowledgeBaseArticle.vue
- desk/src/pages/knowledge-base/KnowledgeBaseArticleTopNew.vue
> fix(KB): article breadcrumbs fixes

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
Add PR and Issues template to the respository.
> chore: add github templates

- desk/src/pages/TicketNew.vue
- desk/src/pages/desk/AgentRoot.vue
- desk/src/telemetry.ts
Add session recording for when user goes to /my-tickets/new
> fix(telemetry):  session recording

- helpdesk/hooks.py
- helpdesk/setup/setup_wizard.py
- helpdesk/utils.py
1. After onboarding is finished create first agent.
2. Check whether the user is agent or not by using ```  "Agent" in frappe.get_roles(user) ```
> fix: create first agent and check for agent role permission

- desk/src/pages/TicketCustomer.vue
- desk/src/pages/TicketNew.vue
- desk/src/pages/ticket/TicketBreadcrumbs.vue
> fix(TicketNew): breadcrumb button UI

- desk/src/main.js
- desk/src/pages/TicketNew.vue
- desk/tsconfig.json
- helpdesk/www/helpdesk/index.py
Add a telemetry event to capture active_site
> fix(telemetry): Add event to capture active_site

- desk/src/components/CommunicationArea.vue
- desk/src/components/ViewControls.vue
- desk/src/pages/TicketAgent.vue
1. Show ticket number in the Title.
2. Show applied filter in the Title.
> fix(ui): show ticket number in title

- desk/src/pages/TicketNew.vue
- desk/src/telemetry.ts
When a ticket is submitted, only capture telemetry event when in customer portal
> fix: new ticket navigation issue

- desk/src/components/ViewControls.vue
- desk/src/components/ticket/TicketsAgentList.vue
- desk/src/pages/TicketsAgent.vue
enhancement of https://github.com/frappe/helpdesk/pull/1918
> feat: allow selected rows to be exported

- helpdesk/search.py
Need to filter in query manually as we do fuzzy search of all words
> fix(HelpdeskSearch): Add custom stopwords

- helpdesk/api/article.py
- helpdesk/hooks.py
- helpdesk/search.py
- requirements.txt
- **fix(HelpdeskSearch): Acquire lock before building index**
- **feat(HelpdeskSearch): Add fallback search of basic nouns in case no results**
- **fix(HelpdeskSearch): Make search optimistic**
> fix(HelpdeskSearch): Optimistically retreive results

- desk/src/components/Settings/Branding.vue
- desk/src/components/Settings/EmailAccountList.vue
- desk/src/components/Settings/EmailEdit.vue
- desk/src/components/Settings/emailConfig.ts
- helpdesk/api/settings.py
> fix: add frappe mail support

- desk/src/router/index.js
All users were not being fetched, so added method to fetch users in router.js
> fix: fetch all users before each route

- desk/src/pages/desk/AgentRoot.vue
Change Location of MobileLayout & DesktopLayout from "/Layout" to "/layout"
> fix: change directory location in agent root

- desk/src/components/layouts/Sidebar.vue
- desk/src/components/notifications/Notifications.vue
- desk/src/pages/MobileNotifications.vue
change notification unread style color from dark gray to light blue
> fix: change notification unread color to light blue

- desk/src/components/Settings/Branding.vue
Reactivity for Favicon in Branding tab in Settings Modal was broken.
This PR resolves the issue
> fix: favicon reactivity in settings modal

- helpdesk/api/article.py
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.js
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
- helpdesk/helpdesk/doctype/hd_synonym/hd_synonym.json
- helpdesk/helpdesk/doctype/hd_synonym/hd_synonym.py
- helpdesk/helpdesk/doctype/hd_synonyms/hd_synonyms.js
- helpdesk/helpdesk/doctype/hd_synonyms/hd_synonyms.json
- helpdesk/helpdesk/doctype/hd_synonyms/hd_synonyms.py
- helpdesk/helpdesk/doctype/hd_synonyms/test_hd_synonyms.py
- helpdesk/search.py
-  Make weights configurable on the fly. Needs reindexing. Added btn for same
-  Add synonym detection
- Fix noun detection by converting query to lowercase beforehand
> fix(HelpdeskSearch): Synonyms and other minor improvements

- desk/src/components/AssignmentModal.vue
- desk/src/components/SearchComplete.vue
add custom filters option in search complete,
**useCase:** filter out agents which are not active.
Thanks to #1959 for the suggestion
> fix: add custom filters on query in search complete component

- desk/vite.config.js
> fix: add start url for PWA

- desk/src/components/layouts/Sidebar.vue
- desk/src/pages/ticket/TicketNewArticles.vue
1. Don't show Notifications in Customer Portal
2. Fix styling of search related Articles (Customer Portal)
> fix(styling): search related articles

- desk/src/components/CommentTextEditor.vue
- desk/src/components/EmailEditor.vue
Show Video controls when agent uploads a video.
> fix: show video controls in agent side

- desk/src/components/ViewControls.vue
- desk/src/components/layouts/Sidebar.vue
- desk/src/pages/TicketNew.vue
1. Adjust notification unread icon.
2. Remove divider in View Controls.
3. Make Subject mandatory * color red.
> fix(ui): minor UI changes

- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
These 2 settings should be enabled by default.
> fix: by default new settings should be enabled

- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
Change Sections and Description in "Ticket" Tab of HD Settings.
**Before**
**After**
> fix: hd settings better ui

- docker/docker-compose.yml
- docker/init.sh
Add docker config for setting up helpdesk.
> feat: docker setup

- desk/src/App.vue
- desk/src/main.js
- desk/src/telemetry.ts
- helpdesk/api/telemetry.py
telemetry was being stored in local storage, because of which if new posthog data was stored, the data was still going to older version.
This PR fixes the issue.
> fix: telemetry

- desk/src/pages/TicketAgent.vue
- desk/src/pages/TicketCustomer.vue
- helpdesk/helpdesk/doctype/hd_form_script/hd_form_script.json
- helpdesk/helpdesk/doctype/hd_form_script/hd_form_script.py
- helpdesk/helpdesk/doctype/hd_ticket/api.py
1. Feature to update a field value via custom scripts (HD Form Action).
2. Add support for Custom Actions in customer portal
> feat(customisation): update field value from custom actions

- desk/src/components/ticket/TicketsListView.vue
Customer Portal will also have functionality to export the tickets.
Just select the tickets you want to export or you can use export all tickets.
> fix: allow export functionality for customer portal also

- desk/src/components/ticket/index.ts
- desk/src/pages/Tickets.vue
- desk/tailwind.config.js
Remove deprecated tailwind config
1. preset
2. plugin
> chore: update tailwind config

- desk/src/App.vue
- desk/src/components/EmailEditor.vue
- desk/src/components/ListViewBuilder.vue
- desk/src/components/ticket/TicketsListView.vue
- desk/src/components/view-controls/Reload.vue
- helpdesk/api/doc.py
- helpdesk/api/session.py
- helpdesk/helpdesk/doctype/hd_agent/hd_agent.py
- helpdesk/helpdesk/doctype/hd_article/hd_article.py
- helpdesk/helpdesk/doctype/hd_customer/hd_customer.py
- helpdesk/helpdesk/doctype/hd_team/hd_team.json
- helpdesk/helpdesk/doctype/hd_team/hd_team.py
- helpdesk/overrides/contact.py
The api "get_list_data" sends rows key to the client, which is not required in any of the list views.
So removed it
> fix(api): get_list_data 

- desk/src/components/ticket/TicketAgentActivities.vue
- desk/src/pages/TicketAgent.vue
Make changes to "Tab" component, according to https://github.com/frappe/frappe-ui/pull/251
> fix: update tabs component

- README.md
> Update README.md (there -> their)

- desk/src/pages/MobileTicketAgent.vue
- desk/src/pages/Tickets.vue
Update the tab component in mobile view of single ticket.
> fix: update tab component for mobile view

- desk/src/pages/HRoot.vue
rename knowledge base params name while routing the user
> fix: rename routing param

- desk/src/telemetry.ts
**Issue:**
Telemetry was not being recorded since the recent update in telemetry file due to checking wrong variable.
> fix: telemetry enabled fix

- desk/src/components/CommentTextEditor.vue
- desk/src/components/CommunicationArea.vue
- desk/src/components/EmailEditor.vue
- desk/src/pages/TicketCustomer.vue
- desk/src/pages/desk/team/TeamSingle.vue
- desk/src/pages/ticket/TicketCommunication.vue
- desk/src/stores/agent.ts
1. Persist comment and email for each ticket separately.
2. Cmnd + Enter / Ctrl + Enter shortcut to submit mail or comment.
3. Search functionality while adding members in a team
> fix(ux): add shortcut to submit comment or email

- desk/src/components/UniInput2.vue
- desk/src/components/ViewBreadcrumbs.vue
- desk/src/components/layouts/Sidebar.vue
Styling fixes to Custom Views breadcrumbs and sidebar
> fix(styles): custom views sidebar and breadcrumbs

- desk/src/components/UniInput2.vue
Link field onChange event was not working in the Custom Fields component
> fix: emit link field event and value

- desk/src/components/ListViewBuilder.vue
- desk/src/components/layouts/MobileSidebar.vue
- desk/src/components/layouts/Sidebar.vue
- desk/src/components/view-controls/QuickFilters.vue
- desk/src/pages/desk/team/Teams.vue
- desk/src/pages/knowledge-base/KnowledgeBaseAgent.vue
- desk/src/pages/ticket/Tickets.vue
The ListViewBuilder Component was creating "div" instead of "route-link" because the ListView expects a 
"onRowRoute" to render an anchor tag.
> fix: use route-link instead of div in LVB

- desk/src/components/Icon.vue
- desk/src/components/ListViewBuilder.vue
- desk/src/components/index.ts
- desk/src/composables/useView.ts
- desk/src/pages/ticket/TicketAgent.vue
- desk/src/pages/ticket/Tickets.vue
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
1. Add a confirmation dialog while changing a public view to a pinned/private view.
2. Add breadcrumbs (custom view) while navigating to single ticket view.
> fix(ux): confirmation for updating public view

- desk/src/pages/ticket/Tickets.vue
This PR solves the bug to make Pinned views public
> fix: allow pinned view to become public

- desk/src/pages/ticket/TicketAgent.vue
- desk/src/pages/ticket/TicketNew.vue
We get 3 toasts when error occurs on the TicketAgent Page. This PR fixes the issue by just removing the onError method in TicketAgent Page and handling the error from main.js file using "fallbackErrorHandler"
> fix: triple error toast issue

- desk/src/components/EmailArea.vue
- desk/src/components/ListViewBuilder.vue
- desk/src/components/UniInput2.vue
- desk/src/components/ticket/ActivityHeader.vue
- desk/src/pages/ticket/TicketAgent.vue
Sometimes, the email displayed in the reply section is wrong. This PR fixes the problem
> fix: wrong email while replying

- desk/src/pages/ticket/TicketNew.vue
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/doctype/hd_ticket_priority/hd_ticket_priority.json
Allow renaming ticket priority
> fix: allow renaming priority

- desk/src/components/CommunicationArea.vue
- desk/src/components/desk/global/NewContactDialog.vue
- desk/src/components/layouts/Sidebar.vue
- desk/src/components/ticket/ActivityHeader.vue
- desk/src/components/ticket/TicketAgentActivities.vue
- desk/src/components/ticket/TicketAgentDetails.vue
- desk/src/components/ticket/TicketAgentSidebar.vue
- desk/src/components/ticket/TicketCustomerSidebar.vue
- desk/src/components/ticket/TicketFeedback.vue
- desk/src/main.js
- desk/src/pages/desk/contact/ContactDialog.vue
- desk/src/pages/desk/team/Teams.vue
- desk/src/pages/ticket/MobileTicketAgent.vue
- desk/src/pages/ticket/TicketAgent.vue
- desk/src/pages/ticket/TicketConversation.vue
- desk/src/pages/ticket/TicketCustomer.vue
- desk/src/pages/ticket/TicketFeedback.vue
- desk/src/pages/ticket/TicketNew.vue
- desk/src/pages/ticket/Tickets.vue
- desk/src/pages/ticket/data.ts
- desk/src/stores/knowledgeBase.ts
- desk/src/stores/notification.ts
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
1. Padding and Margin fixed in Agent and Customer ticket view
2. Show resolution status as paused if ticket is paused
3. Dont show trial banner on customer portal 
4. Remove triple errors from whole Helpdesk using "fallbackErrorHandler" from frappe-ui
> fix(styles): agent and customer ticket view

- desk/src/components/ticket/TicketAgentDetails.vue
Only show paused status for tickets which have not failed SLA
> fix: paused condition for failed sla

- desk/src/components/CommentBox.vue
- desk/src/components/CommentTextEditor.vue
- desk/src/components/CommunicationArea.vue
- desk/src/components/EmailArea.vue
- desk/src/components/EmailEditor.vue
- desk/src/components/desk/global/AddNewAgentsDialog.vue
- desk/src/components/frappe-ui/Link.vue
- desk/src/components/ticket/ActivityHeader.vue
- desk/src/components/ticket/TicketAgentActivities.vue
- desk/src/components/ticket/TicketAgentSidebar.vue
- desk/src/components/ticket/TicketMergeModal.vue
- desk/src/components/ticket/TicketSplitModal.vue
- desk/src/pages/desk/team/TeamSingle.vue
- desk/src/pages/knowledge-base/Article.vue
- desk/src/pages/ticket/MobileTicketAgent.vue
- desk/src/pages/ticket/TicketAgent.vue
- desk/src/router/index.ts
- desk/src/stores/auth.ts
- desk/src/stores/user.ts
- desk/src/types.ts
- helpdesk/helpdesk/doctype/hd_ticket/api.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/utils.py
> feat: Split & Merge Ticket

- desk/src/components/ListViewBuilder.vue
- desk/src/components/layouts/Sidebar.vue
- desk/src/components/view-controls/Filter.vue
- desk/src/components/view-controls/QuickFilters.vue
- desk/src/pages/ticket/TicketAgent.vue
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
1. Re-open email is sent if ticket is newly created, should send only when customer replies
2. Overflow sidebar issue when a lot of pinned/public views are present
3. Automatic update filters for default view
> fix: send re-open ticket not on new ticket creation

- desk/src/pages/ticket/TicketAgent.vue
toast isn't shown when an error occurs while creating a ticket
> fix: show toast when ticket fails to update

- desk/src/composables/formCustomisation.ts
Add async support for Form Script.
> fix: async support in form script

- desk/src/components/desk/global/NewContactDialog.vue
- desk/src/pages/desk/contact/ContactDialog.vue
1. Implemented code changes as part of Feature Request #2239.
https://github.com/user-attachments/assets/3170a0bc-5954-40e7-b78e-81b39c8d8190
2. Added a new “Customer” field in the Contact Dialog, allowing users to update the associated customer even after the contact has been created.
https://github.com/user-attachments/assets/dc1289a7-64c0-4b10-b1cd-5ba02e78d3e1
3. Invite contacts as users from the Contact modal (This is temporary and will be removed when "Invitation Flow" will be introduced.
https://github.com/user-attachments/assets/d123d42e-cf9a-4ae2-a876-c444cd611717
> feat: contact dialogs refactor

- helpdesk/helpdesk/doctype/hd_ticket/api.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/doctype/hd_ticket_activity/hd_ticket_activity.json
refer https://github.com/frappe/frappe/issues/32287 and https://github.com/frappe/helpdesk/issues/2279
> perf: misc int PK + indexing optimizations

- desk/src/components/EmailEditor.vue
- pyproject.toml
> chore: pin redis version

- desk/src/components/UniInput2.vue
For Select & Link fields
value prop is used
and for 
data field model-value prop is used
> fix: use value and modelValue both

- helpdesk/api/dashboard.py
Correct query for calculating avg of rating
> fix: query for calculating avg rating

- desk/yarn.lock
- yarn.lock
> chore: update yarn.lock file

- .pre-commit-config.yaml
- desk/package.json
- desk/src/components/Settings/agents.ts
- desk/src/components/ticket/TicketAgentDetails.vue
- desk/src/main.js
- desk/src/pages/desk/contact/ContactDialog.vue
- desk/src/utils.ts
- desk/yarn.lock
- helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/doctype/hd_ticket_priority/hd_ticket_priority.py
1. Added Counter in Single Ticket View for better UX
https://github.com/user-attachments/assets/826e9eb9-bda3-4828-9018-99a974725040
2. Better Validations for SLA
- When a priority is added, show a message to add it in SLA.
- Refactor validations of the SLA doctype
- If any priority is present in the Master, but not in SLA, show a message dialog.
- When a SLA is changed on a ticket, show a message toast in the frontend.
3. Show proper calculation of SLA in the frontend
4. Update frappe-ui
5. Use Link component to get Customers in Contact Dialog
6. Correct query to get `tickets_to_close` in auto close tickets feature
Depends on: https://github.com/frappe/frappe-ui/pull/349 & https://github.com/frappe/frappe-ui/pull/350
> fix: Better SLA validations and error messages

- .mergify.yml
CI for adding support for backporting selected PRs
> fix(ci): add mergify.yml for backporting pr with labels

- desk/src/components/Settings/Assignment Rules/AssignmentRuleView.vue
> fix: duplicate error handling

- desk/src/components/UniInput.vue
- desk/src/components/layouts/Sidebar.vue
1. Use frappe-ui Autocomplete
2. Gap in bottom part of sidebar
> fix: style changes

- desk/src/components/EmailArea.vue
- desk/src/components/Settings/FieldDependency/FieldDependencyList.vue
- desk/src/components/UniInput.vue
- desk/src/components/layouts/Sidebar.vue
- desk/src/types.ts
Show placeholder while creating tickets, the value of the placeholder is stored in HD Ticket template => default document
> fix: show placeholder in fields while creating tickets

- desk/src/components/notifications/Notifications.vue
- desk/src/pages/dashboard/Dashboard.vue
- helpdesk/api/dashboard.py
- helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py
- helpdesk/patches.txt
- helpdesk/patches/add_status_category_to_tickets.py
1. Moving from paused state to paused state was causing `on_hold_since` field to be set as None
2. Dashboard calculation
3. Patch for adding data in `status_category`
> fix: issues due to custom status & frappe-ui upgrade

- desk/src/stores/notification.ts
**Issue:**
Notifications are not fetched sometimes, and the reason is we send "userId" filter to the Notification Resource.
The problem is that, when the notification resource is fetched, user resource is not fetched.
**Solution:**
Watch the "hasDeskAccess" variable, if that is true, it means resource is fetched, and then we update filter of the resource and fetch the Notification Resource
> fix: fetch notifications after the user is fetched

- desk/src/components/TicketField.vue
- desk/src/components/ticket-agent/TicketDetailsTab.vue
replace variable "readonly" with "read_only" while finding whether the field is a readonly field or not
> fix: respect read_only fields
