frappe/helpdesk

- desk/src/pages/desk/Desk.vue
- frappedesk/api/setup.py
After creating the site and completing the initial setup the session user "Admininstrator" is switched to the newly created Agent.
> feat: switch admin to agent user after signup

- desk/src/components/portal/NavBar.vue
The top navbar items did not consider parent/children layout, it showed all the items in navbar table
The child items in the navbar table are shown in the dropdown list of the parent navbar item
> fix: navbar items issue in support portal

- desk/src/components/desk/ticket/CommentCard.vue
- desk/src/components/global/CustomTextEditor.vue
Issue: Text formatting did not reflect after submitting the comment, also the text size in text editor and the conversation / comment cards where different
Comment typed in the text editor
Comment Card
Text Editor
Comment Card
Text Editor (_text size changed_)
> fix: text formating issue in comments

- frappedesk/frappedesk/doctype/frappe_desk_settings/frappe_desk_settings.json
- frappedesk/patches.txt
- frappedesk/patches/mark_track_service_level_agreement_true.py
**Issue**: the default value for track_service_level_agreement was set as 0. after renaming Support Settings to Frappe Desk Settings, the value for track_service_level_agreement got changed from 1 to 0
**Fix**: add patch to change track_service_level_agreement back to 1, and mark track_service_level_agreement as default 1
> fix: service level agreement not set to ticket issue

- desk/src/pages/desk/Desk.vue
Resolves #609 
also, this issue was the reason no agents were shown in the assignee drop-down inside the ticket detail view, this PR will fix this issue too
> fix: issue fetching agent list

- desk/package.json
- desk/yarn.lock
update frappe-ui : `v0.0.54` -> `v0.0.58`
> chore: update frappe-ui

- frappedesk/frappedesk/doctype/ticket/ticket.json
agent_remark field was not used anywhere and hence removed.
> refactor: remove agent_remark field from ticket

- desk/src/components/desk/ticket/InfoPanel.vue
> fix: remove ellipses from email in contact info

- desk/.prettierrc.json
Fixed code formatting not working in vscode due to multiple reference of .prettierrc.json file
> fix: remove multiple reference of prettierrc.json config

- desk/src/pages/desk/Tickets.vue
Tickets that are not read have their subject bold and darkened
> feat: add `read` indication in ticket list row

- desk/src/pages/desk/Tickets.vue
All the tickets which were seen by any user were highlighted
Only the tickets which are not read/seen by the viewing agent will be highlighted
> fix: wrong tickets highlighted as read issue

- desk/src/components/desk/SideBarMenu.vue
Removed extra hover space and added padding to right for consistency
If having the cursor only on logo is needed, i'll update to that. 
Fixes - #371
[Screencast from 14-11-22 06:34:53 PM IST.webm](https://user-images.githubusercontent.com/95645706/201667560-1767f88f-fedc-4212-85c6-3f471cb9939e.webm)
> remove extra hover space from f-desk logo

- frappedesk/frappedesk/doctype/agent/agent.py
- frappedesk/frappedesk/doctype/agent_group/agent_group.py
- frappedesk/frappedesk/doctype/frappe_desk_settings/frappe_desk_settings.py
- frappedesk/patches.txt
- frappedesk/patches/mark_assignment_rule_disabled_if_no_agents_is_active.py
- frappedesk/setup/install.py
Resolves #823
What this does:
- marks the assignment rule as disabled if no active agents belong to the rule
- marks assignment rules related to agent groups as disabled by default, which gets enabled when agents are added to the group
- the base support rotation rule is also marked as disabled by default, and gets enabled only if there is any active agents preset
Added patches to disable / enable existing assignment rules
> fix:  assignment rule user list index out of range issue

- desk/src/components/desk/global/AddNewAgentsDialog.vue
Support agent email addresses with multiple subdomains (e.g., user@some.domain.com) and which start with numbers (e.g., user@6ceed.com)
> Update regex for agent email addresses

- desk/src/components/desk/ticket/InfoPanel.vue
Before: clicking on `Open Tickets` drop panel throw some error and did not show the tickets list
After: this issue is fixed, and the ticket list can be seen when clicked
> fix: contact name issue in info-panel

- frappedesk/frappedesk/doctype/frappe_desk_settings/frappe_desk_settings.json
- frappedesk/frappedesk/doctype/ticket/ticket.py
- frappedesk/patches.txt
- frappedesk/patches/add_default_ticket_type.py
- frappedesk/setup/install.py
Resolves #901 
this can be configured from `Frappe Desk Settings` > `Default Ticket Type`
by default its set a `Question`
added patch to set the default value for old users
> feat: add default ticket type, in fd settings, with `Question` as default one

- desk/src/components/desk/global/CustomIcons.vue
- desk/src/components/desk/ticket/ConversationCard.vue
- desk/src/components/desk/ticket/Conversations.vue
- desk/src/pages/desk/Ticket.vue
- frappedesk/api/ticket.py
- frappedesk/frappedesk/doctype/ticket/ticket.py
Resolves https://github.com/frappe/helpdesk/issues/945
1.User will have the ability to add cc and bcc in ticket conversation reply.
2. Cc and bcc values will be displayed in ticket conversation
> feat: cc and bcc in ticket conversation reply

- desk/src/components/global/TabButtons.vue
- desk/src/components/global/kb/EditableBlock.vue
- desk/src/pages/desk/kb/Articles.vue
Replaced toggle with icons in knowledge base with tab buttons. Currently it is hard to understand the toggle between articles and web view in the knowledge base.
Resolves #961
https://user-images.githubusercontent.com/73826691/215023439-74ff4d21-25be-4a0f-80d6-e5669a8d6f8a.mp4
> fix: replace toggle with icon in knowledge base with tab buttons

- desk/src/pages/desk/Tickets.vue
We don't have to explicitly set font size since default size is good enough
ref: https://github.com/frappe/helpdesk/issues/958
> fix(ui): tickets: id size

- desk/src/pages/desk/Desk.vue
- frappedesk/frappedesk/doctype/agent/agent.json
Recent changes in frappe framework
(https://github.com/frappe/frappe/pull/19533) broke agent list fetching for us. Regardless, I think it is better to explicitly have a field in doctype itself.
> fix: agent: explicitly fetch image from `User`

- desk/src/components/global/AgentAvatar.vue
UI will crash outright without any warnings if it is unable to render agent avatar (due to missing agent). It is better to handle this case (silently).
> fix(ui): missing agent for avatar

- desk/src/components/desk/settings/teams/TeamInfo.vue
- frappedesk/extends/client.py
- frappedesk/frappedesk/doctype/agent_group/agent_group.json
- frappedesk/frappedesk/doctype/agent_group/agent_group.py
- frappedesk/frappedesk/doctype/frappe_desk_settings/frappe_desk_settings.json
- frappedesk/frappedesk/doctype/ticket/ticket.py
- frappedesk/hooks.py
This PR aims to implement filter tickets by agent group (https://github.com/frappe/helpdesk/issues/973)
This is achieved by having an API filter, instead of framework level user permissions. Using latter method might result in unwanted entries in user permissions
This PR also did a minor refactor to `TeamInfo.vue` whose core logic remains the same
The current behaviour is
- Get agent groups (teams) of current user
- Fetch tickets of above agent groups
- Fetch tickets without any assigned agent group
Pending
> feat: filter by agent group (team)

- frappedesk/extends/qb.py
`get_query` from version 14 of frappe framework does not seem to support `order_by`. This PR will add this field to our version of `get_query`
> fix(get_query): add `order_by` for v14

- frappedesk/extends/qb.py
Currently, if there is no specified `order_by` field, the query fails.
This PR adds fallback values for order by field and direction, `modified` and `desc`
> fix(api): fallback value for order by field

- desk/src/pages/desk/Desk.vue
- frappedesk/frappedesk/doctype/frappe_desk_settings/frappe_desk_settings.json
This PR add a checkbox in "Frappe Desk Settings" to suppress default email toast. This toast shown whenever you are logged into dashboard and there is no default email set
> <img width="307" alt="image" src="https://user-images.githubusercontent.com/28098330/222981183-ad23dcf0-1776-4b7f-9df9-45b636f3675e.png">
> fix(ux): suppress default email toast

- desk/src/components/desk/ticket/Conversations.vue
- frappedesk/frappedesk/doctype/frappe_desk_comment/frappe_desk_comment.py
- frappedesk/frappedesk/hooks/communication.py
- frappedesk/hooks.py
The event frontend listen to, `list_update` is not reliable. Hence no updates reach desk
Trigger a custom event whenever there is a new doc, currently applied to
- `Frappe Desk Comment`
- `Communication` (from `Core`, via hooks)
> fix(ux): realtime communication for ticket: comments/conversations

- frappedesk/frappedesk/doctype/frappe_desk_settings/frappe_desk_settings.json
- frappedesk/frappedesk/doctype/ticket/ticket.py
This PR adds a check in `Frappe Desk Settings` to decide if the reply e-mail should be sent instantly (instead of adding to a queue)
> feat: settings: add a check to instantly send email

- frappedesk/frappedesk/doctype/ticket/ticket.py
This PR explicitly expose e-mail recipients, so recipient can reply to all participants
> feat: expose recipients in e-mail

- desk/package.json
- desk/src/pages/desk/Ticket.vue
- desk/yarn.lock
- frappedesk/frappedesk/doctype/ticket/ticket.py
> feat: email: cc bcc multiple value support

- desk/src/pages/desk/kb/Articles.vue
- frappedesk/extends/qb.py
- frappedesk/frappedesk/doctype/article/article.py
- frappedesk/frappedesk/doctype/category/category.py
This PR moves list fetching logic (fields and filters in query) to api (python)
> refactor(kb): list query

- desk/src/pages/desk/Ticket.vue
When adding a comment, the comment won't appear on the conversation thread after create a comment. The agents need to refresh to see the added comment.
This PR fixes it.
> [FIX] Bug: when adding a comment, the comment won't appear.

- desk/src/pages/portal/ticketing/Ticket.vue
- desk/src/utils/editor.ts
closes https://github.com/frappe/helpdesk/issues/1136
> fix(ux): customer portal: disallow empty messages

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- remove container from reply email
- use template only if ticket is raised via customer portal
> fix(ux): use template only if raised via customer portal

- desk/src/App.vue
- desk/src/components/global/LoginBox.vue
- desk/src/router.js
- desk/src/stores/config.ts
- helpdesk/api/config.py
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
This PR
- Adds a field in `HD Settings` - `brand_logo` which can be used to attach an image
- This image is then used in auth pages (Login and Signup)
> 
_Logo taken from https://commons.wikimedia.org/wiki/File:Wikipedia_name_logo.png_
> feat: brand logo for auth pages

- helpdesk/api/ticket.py
When clicking on `TICKET HISTORY` on a ticket page, there is an error saying, a table Ticket Activity doesn't exist.
This PR fix this issue. By changing `tabTicket Activity` to `tabHD Ticket Activity`.
> fix: Ticket Activity doesn't exist.

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Change the email subject which is replied by an agent. Example is below.
from `Re: Example email subject 10`
to `Re: Example email subject (#10)`
Note: 10 is a ticket number.
This makes emails that sent to customers look more slick and easy to understand.
> Modify replied email subject:

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/utils.py
Automatically update ticket status as 'Replied' whenever agent responds
> fix(ux): on agent response: auto mark as 'Replied'

- desk/src/stores/agent.ts
- desk/src/stores/contact.ts
- desk/src/stores/team.ts
- desk/src/stores/ticketPriority.ts
- desk/src/stores/ticketType.ts
This is because frappe-ui defaults to `pageLimit` 20. This is undesirable for stores, since they need `all` entries. As a workaround, a `pageLimit` of 99999 is used.
> fix(ux): stores: set a high number as `pageLimit`

- desk/src/pages/desk/ticket/TopBar.vue
There is nothing to go back to if there is no history. This PR adds a check if there is a way to go back. If not, it will go to the default page
> fix(ux): ticket page: can not back go back if no history

- desk/src/pages/desk/ticket/TicketDetails.vue
- Show save button only if there is a change
- Change background color (darken, `bg-gray-900`)
> fix(ux): ticket details: show save button only if there is a change

- desk/src/pages/desk/ticket-list/NewTicketDialog.vue
Issue:https://github.com/frappe/helpdesk/issues/1178
The issue has been resolved by adding Doctype to the reference in Contact filters.
As the table was not given reference db was throwing ambiguous errors.
error has been solved in this Merge
> fix(ui): Created By field empty issue fixed

- desk/src/pages/desk/ticket/editor/ResponseEditor.vue
- desk/src/stores/config.ts
- helpdesk/api/config.py
> feat: agent portal: response editor: conditionally hide email fields

- helpdesk/extends/client.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- The user cannot access the previously created ticket on the customer portal view. The SQL exception that occurred when loading the view was what caused this problem.
- It was noticed that even if the fields were set for the desired column, the final query still had an additional `*`.
- Add conditional check for adding filters to the final query.
Issue ticket: #1254
> Resolve customer portal view issue

- desk/src/components/desk/sidebar/SideBar.vue
- desk/src/components/desk/sidebar/SidebarLink.vue
> feat(ui): sidebar: beta badge

- desk/src/components/desk/kb/ArticleDetails.vue
- desk/src/components/desk/settings/SettingsSideBarMenu.vue
- desk/src/components/desk/settings/canned_responses/CannedResponseInfo.vue
- desk/src/components/desk/settings/canned_responses/CannedResponseListItem.vue
- desk/src/components/desk/settings/emails/EmailListItem.vue
- desk/src/components/desk/settings/policies/SlaPolicyListItem.vue
- desk/src/components/desk/settings/teams/TeamInfo.vue
- desk/src/components/desk/settings/ticket_types/TicketTypeInfo.vue
- desk/src/components/global/kb/ArticleCard.vue
- desk/src/components/global/kb/ArticleMiniList.vue
- desk/src/components/global/kb/LayoutSwitcher.vue
- desk/src/components/global/kb/SearchSection.vue
- desk/src/components/global/ticket_list_item/Subject.vue
- desk/src/pages/desk/kb/Articles.vue
- desk/src/pages/desk/sla/SlaPolicies.vue
- desk/src/pages/desk/ticket-list/TicketSummary.vue
- desk/src/pages/desk/ticket/OpenTicketList.vue
> chore: replace: `router-link` with `RouterLink`

- helpdesk/consts.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/doctype/hd_ticket/patches/set_ticket_type.py
- helpdesk/helpdesk/doctype/hd_ticket_type/hd_ticket_type.json
- helpdesk/helpdesk/doctype/hd_ticket_type/hd_ticket_type.py
- helpdesk/patches.txt
- helpdesk/setup/install.py
- helpdesk/setup/ticket_type.py
This PR will
- Apply a ticket type even if no default is specified
- Refactor common hooks in ticket controller
> feat: fallback ticket type

- helpdesk/helpdesk/doctype/hd_agent/hd_agent.py
Do not add `System Manager` role when creating an `Agent`
> fix(ux): new agent: do not add `System Manager` role

- helpdesk/helpdesk/doctype/hd_ticket_template_docfield/hd_ticket_template_docfield.json
Only allow `Link` and `Select`
https://github.com/frappe/helpdesk/issues/1326
> fix(doctype): template field types

- desk/src/pages/desk/ticket/TicketHistory.vue
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Earlier, Ticket history didn't show which user has done the changes.
(Message for all the Update has been slightly changed)
Now, Ticket History shows which user has done the changes (Now it works as shown in Helpdesk Homepage UI)
Also Ticket creation message has been updated.
> Username added in Ticket history

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
since, now a ticket can be accessed by two different contacts under same customer,
if User A has raised a ticket, and User B tries to reply on the same ticket, then the communication is inserted shows User A's name and image
> fix: set session user as sender when creating a reply

- helpdesk/helpdesk/utils/email.py
> fix(ux): email accounts: ignore protocol

- helpdesk/helpdesk/doctype/hd_ticket/api.py
closes https://github.com/frappe/helpdesk/issues/1405
> fix(api): ticket: handle out of bounds (not found)

- desk/src/pages/desk/AgentRoot.vue
- desk/src/pages/desk/DeskDashboard.vue
- desk/src/pages/desk/agent/AgentList.vue
- desk/src/pages/desk/canned_response/CannedResponseList.vue
- desk/src/pages/desk/contact/ContactList.vue
- desk/src/pages/desk/customer/CustomerList.vue
- desk/src/pages/desk/email/EmailList.vue
- desk/src/pages/desk/escalation/EscalationRuleList.vue
- desk/src/pages/desk/sla/SlaList.vue
- desk/src/pages/desk/team/TeamList.vue
- desk/src/pages/desk/ticket-list/PresetFilters.vue
- desk/src/pages/desk/ticket-list/TicketList.vue
- desk/src/pages/desk/ticket/TicketSingle.vue
- desk/src/pages/desk/ticket_type/TicketTypeList.vue
- desk/src/pages/knowledge-base/KnowledgeBase.vue
- desk/src/pages/portal/TicketList.vue
- desk/src/pages/portal/TicketNew.vue
- desk/src/stores/config.ts
- helpdesk/api/config.py
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
**Don't use `brand_favicon` and `helpdesk_name`!**
Branding helps in customisation but it breaks product integrity. From this PR on, its not possible to have custom favicon and name. Custom logo can be used but will be removed at a later stage
closes: https://github.com/frappe/helpdesk/issues/1524
> Remove branding - favicon & custom name

- helpdesk/patches/rename_doctypes_prefix_with_hd.py
Ref: https://frappecloud.com/app/agent-job/cab67ab0d4
> fix: Don't attempt rename if old DocType doesn't exist

- desk/src/pages/ticket/TicketAgentActions.vue
- helpdesk/helpdesk/doctype/hd_action/hd_action.js
- helpdesk/helpdesk/doctype/hd_action/hd_action.json
- helpdesk/helpdesk/doctype/hd_action/hd_action.py
- helpdesk/helpdesk/doctype/hd_action/test_hd_action.py
This is a customisation which lets you add arbitrary button on top of ticket page (agent portal only). JavaScript snippets can be run (basic). This helps for things like
- Open Frappe Cloud dashboard from site name
- Search Google/Wiki with ticket subject
This is available for only tickets. The scripting is basic too. Expect changes/additions later
closes: https://github.com/frappe/helpdesk/issues/1505
> feat: actions

- helpdesk/helpdesk/doctype/hd_ticket/api.py
```
Traceback (most recent call last):
File "apps/frappe/frappe/app.py", line 95, in application
response = frappe.api.handle()
File "apps/frappe/frappe/api.py", line 54, in handle
return frappe.handler.handle()
File "apps/frappe/frappe/handler.py", line 47, in handle
data = execute_cmd(cmd)
File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File "apps/frappe/frappe/__init__.py", line 1622, in call
return fn(*args, **newargs)
File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/api.py", line 62, in get_one
"assignee": get_assignee(ticket._assign),
File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/api.py", line 87, in get_assignee
if len(j) < 1:
TypeError: object of type 'NoneType' has no len()
index-c9e099b3.js:269:1597 …
```
> fix: unable to view ticket if no assignee

- helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py
It's hard to figure out what's the problem without exception.
> fix: share why condition is wrong

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/doctype/hd_ticket/patches/first_responded_on.py
- helpdesk/patches.txt
This used to be set from `Replied` status. The logic is then changed to fetch first response from communication instead
> patch(ticket): first response from communication

- helpdesk/utils.py
Currently, system doesn't check if the fetched contact belongs to an HD Customer or not.
Added a where condition to fetch only HD Customer.
> fix: fetch only HD Customer contacts

- desk/src/pages/ticket/TicketCustomer.vue
- desk/src/pages/ticket/TicketFeedback.vue
On Resolve and Close, change the status to close
[On Resolve and Close, change the status to close](https://github.com/frappe/helpdesk/assets/30501401/fbc1624b-2ab4-437a-9b29-f8d90fb8c227)
> fix: change Resolve btn to 'Resolve and Close' on portal

- helpdesk/helpdesk/doctype/hd_notification/hd_notification.json
- helpdesk/helpdesk/doctype/hd_notification/hd_notification.py
- helpdesk/mixins/mentions.py
- helpdesk/setup/install.py
- helpdesk/templates/emails/notification.html
Fixes https://github.com/frappe/helpdesk/issues/1655
> fix: show comment in email

- desk/src/pages/ticket/TicketCustomerTemplateFields.vue
In customer ticket, Tooltip with datetime will appear on hover at First Response and Resolution labels
closes https://github.com/frappe/helpdesk/issues/1678
> feat(ticketcustomer): show datetime on hover on sla times

- desk/src/pages/ticket/TicketNew.vue
> chore: added temporary banner for offsite

- desk/src/pages/ticket/TicketNew.vue
Issue: #1698
Updated the code to take the ticket type input.
> feat: add support for retrieving the ticket type when creating a new ticket

- desk/src/pages/ticket/TicketTextEditor.vue
When we upload an attachment in ticket `doctype` as parameter is passed, which will breaks the file upload
https://github.com/frappe/frappe/blob/develop/frappe/core/doctype/file/file.py#L140
While uploading attachments, we do not need to pass the `doctype` parameter, it will be automatically handled by `create_communication_via_contact` method
issue ref: #1695 ,#1712
> fix: Attach attachments after the ticket is saved

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
On HD Ticket, if you change status from Replied to Open, it will show following error,
```
File "apps/helpdesk/helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py", line 194, in on_update
agent = json.loads(self._assign)
^^^^^^^^^^^^
AttributeError: 'HDTicket' object has no attribute '_assign'
```
This PR fix it by using get_assigned_agent() instead.
> fix: error when change status replied to open due to self._assign

- desk/src/components/UniInput2.vue
- desk/src/components/ticket/TicketAgentFields.vue
- desk/src/pages/desk/team/TeamSingle.vue
**Issue:**
When adding a member into the team the dialog shows empty
**Reason:**
We were looping over wrong property in agentStore.
**Solution:**
use agentStore.agents.data instead of agentStore.options
&
if no members are present show them a dialog with a link to add new agents
> fix: add members in team from UI

- desk/src/components/LayoutHeader.vue
- desk/src/pages/TicketAgent.vue
- desk/src/pages/desk/team/TeamSingle.vue
**Issue:**
1. The breadcrumb UI looks cheap (it has a button in the breadcrumb) and has an on click functionality to update the "subject" of the ticket, which does not make any sense.
2. When the subject of the ticket is too long there is an overflow in screen.
> fix: header breadcrumb styling

- .github/workflows/lint.yml
- desk/src/components/desk/global/NewCustomerDialog.vue
- desk/src/pages/desk/contact/ContactDialog.vue
- desk/src/pages/desk/customer/CustomerDialog.vue
- desk/src/pages/desk/customer/CustomerList.vue
- helpdesk/extends/client.py
- package.json
- yarn.lock
**Issue:**
1. When we add a new customer, the page reloads.
2. When we update a contact, the dialog does not close.
3. Failing CI, cause of
-  old semgrep version.
- Old eslint-plugin-vue package
**Solution:**
1. Fixed reactivity in CustomerList and the relevant components.
2. Upgraded eslint-plugin-vue to latest version
3. Upgraded semgrep to latest version
> fix: reactivity in customer page

- desk/src/App.vue
- desk/src/pages/KnowledgeBaseArticle.vue
- desk/src/pages/TicketNew.vue
- desk/src/pages/ticket/TicketNewArticles.vue
- desk/src/router/index.js
- desk/src/telemetry.ts
- helpdesk/api/article.py
**Telemetry**
- 3 new events are captured with data
1. helpdesk_new_ticket_page => also contains the user
2. helpdesk_article_viewed =>
```
data: {
user: authStore.userId,
article: data.name,
title: data.title,
},
```
3. helpdesk_ new_ticket_submitted =>  
```
data: {
user: userID,
ticketID: data.name,
subject: subject.value,
description: description.value,
customFields: templateFields
}
```
- Page recording for the whole app.
- Initialise telemetry only once in App.vue instead of initialising on every page route.
**Search**
- Change minimum search length to 3.
- In Customer Portal, while creating a new ticket, hide the Text Editor if there is no subject.
> fix: improve telemetry and article search

- desk/yarn.lock
change cheerio versioning to fixed instead of `^`, coz of node version incompatibility.
> fix(dep): fixed cheerio version

- desk/package.json
- package.json
add cheerio in package.json resolutions to support node version 18.16 instead of >18.17
> fix(dep): add cheerio in resolutions

- helpdesk/setup/setup_wizard.py
When onboarding is completed we create an agent from the user, If no user is found then dont create an agent.
Helpdesk Setup Error 
closes #1908
> fix: if new user not found then return

- helpdesk/hooks.py
Dependent on https://github.com/frappe/frappe/pull/27292
Updated hooks.py to include helpdesk app in apps page
> fix: add helpdesk to apps page

- desk/src/pages/TicketAgent.vue
**Before**
We get errors like these, which doesn't actually tell why the error was thrown
**After**
Show the error message properly
closes #1840
> fix: show proper error message

- desk/src/components/command-palette/CP.vue
- desk/src/pages/KnowledgeBaseArticle.vue
- desk/src/pages/ticket/TicketNewArticles.vue
- helpdesk/api/article.py
- helpdesk/search.py
~- [ ] Fix ticket id search~ Not doing this as it's too out of the way. Filter already exists for this anyway
> fix(HelpdeskSearch): Improve search of knowledge base articles

- desk/src/pages/KnowledgeBaseArticle.vue
If the URL has a hash, that means we should scroll the page to where that heading is located in the DOM
> fix: scroll to view from Hash

- desk/src/pages/ticket/TicketNewArticles.vue
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
**Issue:**
Even tho the resolution was provided and if fulfilled, in the List view the status was showing as failed / in an hour.
**Reason**
The calculation we did in the frontend(list view) was based on a field called "resolution_date" which was not present in the default fields which were fetched.
**Solution:**
Add "resolution_date" field in default fields
> fix: add resolution_date default field

- desk/src/pages/KnowledgeBaseArticle.vue
- desk/src/pages/knowledge-base/KnowledgeBaseSubcategory.vue
**Issue:**
While navigating to article page from article sub category, the article component gets async data in the breadcrumb which causes the following issue
**Reason:**
In breadcrumbs the route is coming asynchronously, hence the error.
**Fix:**
Get article's category and sub category from query params.
> fix: get article category and sub category from query params

- desk/src/pages/knowledge-base/KnowledgeBaseCategoryNew.vue
**Summary**
This PR addresses an issue in the Knowledge Base category creation dialog where form fields (title, description, and icon) were not being reset after successfully creating a new category.
**Changes**
- Implemented a reset for form fields only after a new category is successfully created.
- No changes were made to the behavior when the dialog is closed without creating a category; the form data remains intact, allowing users to continue their input if the dialog is reopened.
**Testing**
- Verified that the form fields are reset only after successful creation of a category.
- Confirmed that form data persists if the dialog is closed without creating a category.
**Impact**
The form fields in the Knowledge Base category creation dialog will now reset only after a successful …
> Fix: Reset Form Fields After Creating a New Category in Knowledge Base from Agent Portal

- helpdesk/api/article.py
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.py
- helpdesk/helpdesk/doctype/hd_stopword/hd_stopword.js
- helpdesk/helpdesk/doctype/hd_stopword/hd_stopword.json
- helpdesk/helpdesk/doctype/hd_stopword/hd_stopword.py
- helpdesk/helpdesk/doctype/hd_stopword/test_hd_stopword.py
- helpdesk/helpdesk/report/ticket_search_analysis/ticket_search_analysis.js
- helpdesk/helpdesk/report/ticket_search_analysis/ticket_search_analysis.json
- helpdesk/helpdesk/report/ticket_search_analysis/ticket_search_analysis.py
- helpdesk/search.py
-  Add report to iteratively evaluate search
- Add doctype for additional stopwords without adding it in code
- Search fixes
- Use OR search for when AND search fails
- Try noun phrase search before trying noun search
- Search substrings instead of fuzzy (both together conflict). It's more intuitive
- Clean input query better
> fix(HelpdeskSearch): Add report to evaluate search and improvements with the same

- desk/src/components/AssignmentModal.vue
- desk/src/components/EmailBox.vue
- desk/src/components/ticket/TicketAgentActivities.vue
- desk/src/pages/TicketAgent.vue
1. Overflow was happening because of communication component.
2. While assigning tickets to agent, even inactive agents were being shown.
This PR fixes the above 2 issues.
> fix: communication area overflow

- helpdesk/search.py
- **fix(HelpdeskSearch): Add synonym in redis correctly**
- **fix(HelpdeskSearch): Query for synonym correctly**
> fix(HelpdeskSearch): Use synonyms correctly and add fuzzy back

- desk/src/components/layouts/MobileSidebar.vue
- desk/src/components/ticket/TicketAgentFields.vue
- desk/src/pages/CannedResponses.vue
- desk/src/pages/ticket/TicketNewArticles.vue
Use 'createListResource'  to get the canned responses
> fix: Canned response list view

- desk/src/components/Settings/EmailAdd.vue
- desk/src/components/Settings/EmailEdit.vue
- desk/src/pages/KnowledgeBaseArticle.vue
- desk/src/pages/TicketNew.vue
- desk/src/pages/ticket/TicketNewArticles.vue
> fix(styling): styling in article and email

- helpdesk/helpdesk/doctype/hd_service_level_agreement/hd_service_level_agreement.py
**Issue**
While calculating the total elapsed time of the ticket, i.e from the time ticket was created to the time ticket was closed, we calculated the time in seconds, which resulted in timeouts in alot of scenarios.
**Solution**
To enhance the performance use minutes instead of seconds.
> perf: update ticket elapsed time method to use minutes instead of seconds

- desk/src/components/ColumnSettings.vue
- desk/src/pages/KnowledgeBaseArticle.vue
- helpdesk/api/doc.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Show Custom fields from HD Ticket template doctype in the customer portal, for filtering, sorting and customising layout.
> fix: update the fields shown in new customer portal

- desk/src/pages/TicketCustomer.vue
- desk/src/pages/TicketNew.vue
- helpdesk/helpdesk/doctype/hd_service_level_agreement/utils.py
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Introducing a new HD Setting  called "Allow anyone to create tickets".
If enabled This setting allows anyone to create tickets on your support portal. Useful in cases where you wants users to create tickets via webforms or some external APIs without authentication.
By default the value is 0.
> feat: settings to allow to create tickets without permission

- desk/src/components/CommentBox.vue
- desk/src/components/EmailArea.vue
- desk/src/components/ticket/TicketAgentActivities.vue
- desk/src/components/ticket/TicketAgentContact.vue
- desk/src/pages/KnowledgeBaseArticle.vue
- desk/src/pages/TicketNew.vue
- helpdesk/api/doc.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
1. New Design of Email & Comment
2. Show only custom fields visible to customer in the new customer portal.
3. Center align new ticket page and article page.
4. Fix _assign error.
> fix: customer portal filters

- desk/src/components/TextEditor.vue
- desk/src/pages/KnowledgeBaseArticle.vue
- desk/src/pages/ticket/TicketCommunication.vue
- desk/src/pages/ticket/TicketTextEditor.vue
- desk/src/stores/ticketStatus.ts
- desk/src/tiptap-extensions.ts
**Issue**
In the comment or email box we were not able to access the videos, the reason is tip tap removes additional html attributes.
**Solution:**
In tip tap, use an extension to preserve controls attrbute
> fix: add video controls in video HTML elements

- desk/src/components/Settings/EmailAdd.vue
- desk/src/components/Settings/EmailEdit.vue
- desk/src/components/Settings/emailConfig.ts
- desk/src/types.ts
- helpdesk/api/settings.py
Show "frappe_mail_site" field in Settings Modal
> fix: show frappe_mail_site field while creating Frappe Mail Account

- helpdesk/helpdesk/doctype/hd_ticket_template/api.py
This fix maintains the order in which custom fields were added to the tickets and shows up in the side panel.
> fix: Maintain order of custom fields.

- helpdesk/api/settings.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Whenever a ticket was being created from Email, we were getting this null communication.
> fix: dont create null communication

- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Setting to auto update ticket status to an agent replies on a ticket.
> feat: setting to auto update status on reply

- desk/src/App.vue
- desk/src/pages/TicketCustomer.vue
- desk/src/stores/config.ts
- helpdesk/api/config.py
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
1. Settings to make feedback dialog not mandatory.
2. Show Confirmation Dialog when ticket is closed.
> feat: setting to make feedback mandatory

- desk/src/pages/TicketAgent.vue
- desk/src/pages/TicketCustomer.vue
- desk/src/pages/Tickets.vue
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
This PR includes:
1. Fix to create communication if ticket has description
2. using sockets to update ticket list view and single ticket view
> fix: description communication creation

- desk/src/components/UniInput2.vue
- desk/src/components/ticket/TicketAgentActivities.vue
- desk/src/components/ticket/TicketAgentFields.vue
- desk/src/pages/TicketAgent.vue
> fix(styling): three scrollbars in single ticket view

- helpdesk/helpdesk/doctype/hd_ticket/api.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Double communication was being created when a ticket is created. This PR fixes the issue
> fix: stop duplicate communication in HD Ticket

- desk/src/App.vue
- desk/src/components/EmptyState.vue
- desk/src/components/ListViewBuilder.vue
- desk/src/components/layouts/Sidebar.vue
- desk/src/components/ticket/TicketCustomerSidebar.vue
- desk/src/components/ticket/TicketsListView.vue
- desk/src/pages/CannedResponses.vue
- desk/src/pages/KnowledgeBaseArticle.vue
- helpdesk/setup/welcome_ticket.py
1. Empty State Component
2. Fixes article creation error.
> fix: minor navigation and styling fixes

- desk/src/pages/TicketAgent.vue
- helpdesk/helpdesk/doctype/hd_ticket/api.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
**Issue:**
1. When a ticket was created users attachment were not showing, this is because attachments object was not being passed.
2. When an agent attached a file that file becomes private and the customer is not able to access it. 
**Solution:**
1. Attach tickets object while creating ticket.
2. Attach the file uploaded to the ticket, to share its access with the customers having access to the tickets.
> fix: attachments

- desk/src/components/UniInput2.vue
Set value was call being twice because of Form Control Text area element, so used blur event handler for Textarea component
> fix: add blur handler for text fields

- desk/src/App.vue
- desk/src/components/SidebarLink.vue
- desk/src/pages/TicketAgent.vue
- desk/src/pages/knowledge-base/KnowledgeBaseArticleTopPublic.vue
- desk/src/pages/knowledge-base/KnowledgeBaseArticleTopView.vue
- desk/src/pages/ticket/TicketTextEditor.vue
- desk/src/router/index.ts
1. On customer portal we were calling api to get all_users. So basically anyone with access to Customer Portal would be able to see the user database along with images.
2. Because we get all_users before_route the page load becomes slow, to improve it we will get all_users after routing, to increase performance.
> fix: handle routes properly

- desk/src/components/ticket/TicketsListView.vue
- helpdesk/api/session.py
- helpdesk/helpdesk/doctype/hd_team/hd_team.json
Currently: all users who are logged into the system can access the users api and get all users, which is a very high security breach.
This PR fixes the issue: Only Agents will be allowed to access the get_users API.
> fix: only agents can access users api

- desk/src/index.css
- desk/src/pages/CannedResponses.vue
Improve UI for Canned Response Preview
**Before:**
**After:**
> fix(styles): canned responses preview

- .github/workflows/server-tests.yml
> The cache backend service has been rewritten from the ground up for improved performance and reliability. [actions/cache](https://github.com/actions/cache) now integrates with the new cache service (v2) APIs.
>
> The new service will gradually roll out as of February 1st, 2025. The legacy service will also be sunset on the same date. Changes in these release are fully backward compatible.
>
> We are deprecating some versions of this action. We recommend upgrading to version v4 or v3 as soon as possible before February 1st, 2025.
https://github.com/marketplace/actions/cache#%EF%B8%8F-important-changes
> chore: bump actions/cache to v4

- desk/src/components/CommentBox.vue
- desk/src/components/CommentTextEditor.vue
- desk/src/components/EmailArea.vue
- desk/src/components/EmailEditor.vue
- desk/src/components/HistoryBox.vue
- desk/src/components/layouts/MobileSidebar.vue
- desk/src/components/layouts/Sidebar.vue
- desk/src/components/ticket/TicketAgentActivities.vue
- desk/src/components/ticket/TicketAgentSidebar.vue
- desk/src/pages/TicketAgent.vue
- desk/src/pages/ticket/TicketCustomerTemplateFields.vue
- desk/src/types.ts
- desk/src/utils.ts
- helpdesk/api/doc.py
- helpdesk/helpdesk/doctype/hd_notification/utils.py
- helpdesk/helpdesk/doctype/hd_ticket/api.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
**Issue:**
1. Currently, we use `v-html` for the content box, resulting in an overflow of the ticket like this.
2. Because of this we can't edit the comment.
3. No attachments are shown in the UI.
4. Make Ticket agent activities typesafe.
> refactor: comment box 

- desk/package.json
- yarn.lock
Bump frappe ui version from 0.1.53 to 0.1.105
> chore: bump frappe-ui version

- helpdesk/setup/default_template.py
- helpdesk/setup/install.py
1. Dont create default SLA & HD Ticket Template, if they already exists while installing Helpdesk
> fix: ignore duplicate while installing HD

- helpdesk/patches.txt
- helpdesk/patches/communication_read_perm_agent.py
- helpdesk/setup/install.py
**Issue:**
If a customer attaches file with there email, sometimes the agents are not able to see the attachments
**Reason:**
Agent role does not have read permission on the communication doctype.
**Solution:**
Add perm to read communication while installing Helpdesk, also wrote a patch for the same.
> fix: read permission on communication for attachments

- desk/src/components/CommentBox.vue
- desk/src/components/CommentTextEditor.vue
- desk/src/components/EmailContent.vue
- desk/src/components/EmailEditor.vue
- desk/src/components/TextEditor.vue
- desk/src/components/ticket/TicketAgentActivities.vue
- desk/src/pages/ticket/TicketAgent.vue
- desk/src/utils.ts
**Description:**
Currently, we use Inter font in frappe-ui, which doesn't support all characters in Arabic language.
For e.g
Hello in Arabic is "mrhban" which when wrote in Arabic looks like
But in Inter Font, it looks like:
The difference is subtle (last character), it is something like: 
The first image is:
Hello
The second image is:
Hellu
We can understand the meaning, but it is incorrect.
**Solution:**
The _Arabic characters fall in the Unicode range 0600 - 06FF_.
We can do a REGEX check against the string to understand whether there is Arabic in the string or not. Using this logic, we return the font family. 
This is used in all the places where we have used the text editor
While writing anything in comments or email the editor detects whether arabic is present or not and changes the …
> feat: arabic support in font

- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/hooks.py
Scheduler Job which runs every day at midnight and closes all the tickets that are in replied status for more than "n" number of days.
The number of days threshold is taken from HD Settings doctype.
To enable this feature, go to HD Settings > Ticket Tab > click on "Automatically Close Tickets"
Once you click on the setting, the days threshold field (Auto-close after) field will be visible. Here, you can specify the number of days, the default is set to 14 (Days)
closes: https://github.com/frappe/helpdesk/issues/2210
> feat: auto close tickets after n number of days

- desk/src/components/view-controls/Filter.vue
Earlier the "in" filter used to send this data to backend:
the value of the filter is a single string which should be separated by comma like this:
> fix: split by comma in 'in' fiter

- desk/src/pages/ticket/MobileTicketAgent.vue
- desk/src/pages/ticket/TicketAgent.vue
When we navigate to a ticket from Notifications the email shown is wrong, this PR fixes the issue
> fix: show correct email

- desk/src/components/UniInput.vue
- desk/src/components/ticket/TicketAgentFields.vue
- desk/src/types.ts
- helpdesk/helpdesk/doctype/hd_ticket_template/api.py
Apply filters to link field from property setter and custom fields.
https://github.com/user-attachments/assets/c0274778-b34a-4081-837f-a0aad95727de
When we apply a filter in the desk, it gets stored in link_filters docfield.
We can use this field and fetch it in the frontend to apply filters.
> feat(customisation): filters in link field

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
Ignore validations while force closing tickets using doc.flags.ignore_validate
> fix: ignore validate using doc.flags

- desk/src/components/EmailArea.vue
Fetch correct recipient emails when using reply all in ticket.
Before:
After:
> fix: fetch correct recipient emails when using reply all in ticket

- helpdesk/helpdesk/doctype/hd_notification/hd_notification.py
Due to sockets Notification doctype is loaded on customer portal.
> fix: notifications reload on customer portal

- desk/vite.config.js
This fix addresses an error encountered while starting frontend development using ```yarn dev ``` - 
This update ensures proper relative imports and resolves the issue, allowing the frontend to start without errors.
> fix(vite config): optimize lowlight

- .github/workflows/lint.yml
- desk/src/components/SearchPopover.vue
- desk/src/pages/knowledge-base/KnowledgeBaseCustomer.vue
- desk/src/pages/ticket/TicketNew.vue
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/doctype/hd_ticket_template/api.py
- helpdesk/helpdesk/doctype/hd_ticket_template/hd_ticket_template.json
- helpdesk/templates/emails/new_reply_to_agent.html
1. Pre-fill description while raising tickets.
In the "HD Ticket Template" doctype a new field is introduced called "description_template".
Here user can write a markdown and this template will be shown while raising the ticket.
Whatever the agent writes here:
Gets displayed in the portal while raising the ticket:
2. Send email to the agent when a ticket received a reply
> feat: ticket description template

- helpdesk/api/doc.py
**Issue:**
Ticket restrictions based on teams are currently applied to agents and the Customer Portal. As a result, customers may see incorrect or incomplete ticket data on the portal.
**Solution:**
Apply the team restrictions code only on the Agent Portal.
> fix: only apply team restrictions on the agent side

- desk/src/composables/formCustomisation.ts
- desk/src/pages/ticket/TicketAgent.vue
- desk/src/pages/ticket/TicketCustomer.vue
- desk/src/pages/ticket/TicketNew.vue
Whenever the ticket reloads, the CustomActions disappear automatically. 
The object reference wasn't being passed properly.
> fix: on ticket reload customActions disapper

- desk/src/pages/CannedResponses.vue
Inconsistent padding in canned responses
Before: 
After:
> fix(styles): padding canned responses

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
**Issue:**
When the source of the ticket is Email, the images sent by the agent are not shown in the email.
This is because the images are directly sent in base64 encoding in the markdown syntax.
**Solution**
Using `make` function from the "Communication" doctype to handle tickets created via emails
> fix: use make method for mail tickets

- desk/src/components/Settings/EmailEdit.vue
- desk/src/pages/ticket/TicketNew.vue
- desk/src/pages/ticket/Tickets.vue
- desk/src/router/index.ts
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
**Issue:**
1. Emails are not threaded for the tickets that are created via "Mail", which causes issues in understanding the context
2. No acknowledgement email is sent to the tickets that are created via "Mail"
3. To pull the latest Emails, we have to go to the desk and click on the "Pull Emails" button to get them
**Solution:**
1. Emails are now threaded using "message id" & "in_reply_to" headers for the related emails, only for tickets created via email.
2. Acknowledgement email is sent
3. Pull Emails button is now present on the Frontend
> fix: email threading

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
**Issue:**
When an agent replies to a ticket, we use `frappe.sendmail`, and to initiate the threading we set the `message_id` in the communication document, which is a wrong thing to do since it is unique and is generated automatically. 
**Solution:**
Don't send `message_id` in the params, only send the `in_reply_to` param in `frappe.sendmail`
Related: https://github.com/frappe/frappe/pull/32651
> fix: don't use message-id to send mails

- desk/src/telemetry.ts
I've disabled this on server too, fix this if you want to renable: https://github.com/frappe/helpdesk/issues/2321
> fix: disable invasive posthog configs

- docker/init.sh
Will not work unless Schema is specified
> fix: redis requires schema for uri with bench set command

- desk/src/pages/dashboard/Dashboard.vue
- helpdesk/api/dashboard.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
1. Use `feedback_rating > 0` instead of `IS NOT NULL` since default is 0.  
2. Add tooltip in the frontend for better UX.  
3. To include today’s tickets, increment `to_date` by 1 (e.g., "18-06-2025" → "19-06-2025") as SQL excludes today's entries by default (created before 00:00 hrs).
> fix(dashboard): include today's date & change feedback value logic

- desk/package.json
- desk/src/components/layouts/MobileSidebar.vue
- helpdesk/api/dashboard.py
- helpdesk/helpdesk/doctype/hd_settings/hd_settings.json
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
1. Don't send ack emails on initial sync
2. Make ack emails optional
3. Sort data in bar charts in descending order
4. bump frappe-ui
Depends on: https://github.com/frappe/frappe/pull/33006
> fix: dont sent ack emails on initial sync

- desk/src/pages/ticket/TicketNew.vue
While raising ticket from the Agent portal, agents were not able to see the fields which were hidden from the customers.
> fix: show fields on agent portal creation

- desk/package.json
- desk/src/components/CommentTextEditor.vue
- desk/src/components/EmailEditor.vue
- desk/src/pages/ticket/TicketCustomer.vue
- desk/src/pages/ticket/TicketNew.vue
- desk/src/pages/ticket/TicketTextEditor.vue
- desk/src/utils.ts
- desk/yarn.lock
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
1. Before sending mail to the customer, add 'embed' attribute in the img/video element to handle inline content, 'embed' attribute is important because framework replaces it with `<img src="cid:content_id">` this in turn is displayed as an image in the mail sent to the customer.
2. All media are now private and are attached to the relevant document
2. Add  `uploadFunction` prop in TextEditor to attach the file to the document, basically attaching video/image to the ticket
3. All scenarios are covered to ensure privacy for user's media 
- New ticket raised via portal
- Ticket raised via email
- Reply from agent
- Reply from customer
5. Delete removed attachments from the server
6. Preview images before sending
7. Update frappe-ui to 0.1.168 and update yarn.lock file
> fix(security): private media

- helpdesk/overrides/email_account.py
If the subject is like 
"Ticket #732: We've received your request to"
then the communication gets linked to the ticket number 732  because of:
https://github.com/frappe/frappe/blob/c0c85294362882425361ae6da6d13e0cfde04692/frappe/email/receive.py#L797-L801
> fix: dont create communication for auto generated tickets

- desk/src/main.js
- helpdesk/api/doc.py
- helpdesk/crowdin.yml
- helpdesk/helpdesk/doctype/hd_ticket/api.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/utils.py
This PR adds additional checks related to team permissions on the HD Ticket doctype to ensure consistent permission logic between the list and form views, restricting agents to only access tickets they are authorized to view.
continuation to https://github.com/frappe/helpdesk/pull/2294
> fix: Strict permissions on HD Ticket

- desk/src/components/view-controls/Filter.vue
Resolves the issue associated with [this](https://support.frappe.io/helpdesk/tickets/39853?view=VIEW-HD+Ticket-003) ticket.
All of the `Yes` and `No` values of the filters are converted to `boolean`. This is required for `Check` fieldtype filters, but it breaks `Select` fieldtype filters that have `Yes` and `No` as options. The fix is to just convert `Check` fieldtype filter values.
https://github.com/user-attachments/assets/046a0d5b-216f-4fac-8698-e2f5a712740f
> fix: avoid converting yes-no select filter values to boolean

- desk/src/components/ListViewBuilder.vue
- desk/src/components/view-controls/Filter.vue
- desk/src/components/view-controls/QuickFilterField.vue
- desk/src/components/view-controls/QuickFilters.vue
Closes #2419
> We will have to come up with a better way to sync the filters (or not sync them at all) once we work on [this](https://github.com/frappe/helpdesk/issues/2256) issue.
There are 2 types of filters
Until now, updating quick filters has automatically updated the standard filters, but this update was partial (see [this](https://github.com/frappe/helpdesk/issues/2419) issue). This PR fully syncs the quick filters with the standard filters whenever it makes sense.
https://github.com/user-attachments/assets/a804c464-36e5-470b-a62b-2eb005f47ce3
> fix: sync standard and quick list filters

- desk/src/components/MultiSelectInput.vue
- helpdesk/api/contact.py
It is better to use a custom api to reliably generate a list of contacts for the autocomplete feature in the email editor. The logic is very similar to [Frappe CRM](https://github.com/frappe/crm/blob/c64dcb43b4a2f4063060eb79fda5a2336cb5b341/crm/api/contact.py#L116).
> fix: fetch contacts autocomplete from custom api

- desk/src/components/EmailArea.vue
- desk/src/pages/ticket/MobileTicketAgent.vue
- desk/src/pages/ticket/TicketAgent.vue
- helpdesk/helpdesk/doctype/hd_ticket/api.py
- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/www/helpdesk/index.py
**Issue:**
Currently, when a user replies to a customer email that includes a CC recipient, the reply is being sent to both the customer and the CC'd address. This occurs even when using the standard 'Reply' (single arrow) or 'New > Email' options, which are expected to send the response only to the original sender.
**Solution:**
1. Only send to the CC email when "Reply All" is clicked.
2. Adds Communication delivery status to the UI
3. Add session_user to window object
Closes: https://github.com/frappe/helpdesk/issues/2435
> fix: cc email

- desk/src/main.js
I have spent hours on figuring this out. 
https://github.com/vueComponent/ant-design-vue/issues/7603
> fix: import `createApp` before frappe-ui components

- desk/src/pages/ticket/Tickets.vue
- desk/src/types/doctypes.ts
overflow of the status field in the list view
depends on #2484
> fix(style): overflow of status field in list view

- desk/src/components/view-controls/QuickFilterField.vue
Currently, the quick filter select doesn't hide the placeholder text when a value is selected, which is incorrect.
This PR fixes the issue.
> fix: hide quick filter select's placeholder when a value is selected

- helpdesk/helpdesk/doctype/hd_ticket/hd_ticket.py
- helpdesk/helpdesk/doctype/hd_ticket/test_hd_ticket.py
**Issue:**
When a ticket is received via email, the status of the ticket remains unaffected. If the agent has marked the ticket on "Replied" the ticket will remain in "Replied" status, even after we receive a response from the customer.
**Solution:**
On receiving a response, reopen the ticket's status
> fix: handle email ticket reopen and default status

- desk/src/components/CommunicationArea.vue
Fix a bug in email "reply all" button where "quote", "CC", "BCC" emails were not loading 
***Before***
***After***
> fix: email reply all bug

- desk/src/pages/ticket/TicketFeedback.vue
- helpdesk/helpdesk/doctype/hd_ticket_feedback_option/hd_ticket_feedback_option.json
- helpdesk/helpdesk/doctype/hd_ticket_feedback_option/hd_ticket_feedback_option.py
Add disable field in "HD Ticket Feedback Option" DocType.
**Problem:** 
When modifying feedback options in the Feedback Dialog, renaming existing options causes unintended side effects. Since ticket records reference these options by name, any rename operation automatically updates all historical ticket data, potentially compromising data integrity and audit trails.
**Solution:** 
Instead of renaming options, implement a disabled field for feedback options. While getting options in the frontend, add filters for "disabled:0"
> fix: add disable field to Feedback Option

- desk/src/components/ticket-agent/AssignTo.vue
- desk/src/components/ticket-agent/AssignToBody.vue
- desk/src/components/ticket-agent/TicketDetailsTab.vue
**Issue:**
The assign message in HD ticket history doctype was not recorded properly
**Reason:**
We were checking "resource" length instead of the "Array" length.
> fix: assign history message
